# 🔎 Análise de Consenso entre LLMs

## 1) Setup e Configuração

In [24]:
import sys
from loguru import logger
import pandas as pd
from src.api.schemas.experiment import ExperimentRequest

logger.remove()
logger.add(
    sys.stdout,
    format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>",
    level="INFO"
)

logger.success("✓ Setup completo")

11:42:20 | SUCCESS  | ✓ Setup completo

In [25]:
import json
from pathlib import Path

experiment = "experiment_with_qwen3"

# Load JSON from file
config_path = Path(f"../experiments/{experiment}.json")

with open(config_path, "r") as f:
    config_dict = json.load(f)

# Instantiate Pydantic model
EXPERIMENT_CONFIG = ExperimentRequest(**config_dict)

### - Modelos e prompt

In [26]:
DEFAULT_MODELS = EXPERIMENT_CONFIG.models

### - Configurações de consenso

In [27]:
consensus_cfg = {
    "threshold": 0.8,
    "strategy": "majority_vote",
    "no_consensus_strategy": "flag_for_review",
}

consensus_threshold = consensus_cfg.get("threshold", 0.8)
consensus_strategy = consensus_cfg.get("strategy", "majority_vote")
no_consensus_strategy = consensus_cfg.get(
    "no_consensus_strategy", "flag_for_review"
)

### - Configurações de dataset

In [28]:
dataset_cfg = EXPERIMENT_CONFIG.dataset_config

dataset_split = dataset_cfg.split
combine_splits = dataset_cfg.combine_splits
sample_size = dataset_cfg.sample_size
random_state = dataset_cfg.random_state

### - Configurações de cache

In [29]:
cache_dir = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\.cache"

### - Resultados

In [30]:
results_dir = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\results"

In [31]:
from src.utils.get_latest_results_date import get_latest_results_date

dataset_name = "sst1"  
specific_date = "latest"

if specific_date == "latest":
    specific_date = get_latest_results_date(
        results_dir,
        dataset_name
    )
    
results_dir = Path(results_dir)
results_dataset_path = results_dir.joinpath(dataset_name, specific_date)

## 2) Carregar dados

### - Dataset

In [32]:
from src.utils.data_loader import load_hf_dataset

texts, categories, ground_truth = load_hf_dataset(
    dataset_name=dataset_name, 
    cache_dir=cache_dir,
    dataset_global_config=dataset_cfg
)

logger.info(f"Textos: {len(texts)}")
logger.info(f"Categorias: {categories}")
logger.info(f"Ground truth: {'Sim' if ground_truth else 'Não'}")

11:42:20 | INFO     | Carregando dataset: sst1
11:42:25 | INFO     | Split 'train': 106695 exemplos
11:42:25 | INFO     | Categorias extraídas automaticamente: [0, 1, 2, 3, 4]
11:42:25 | INFO     | Amostra reduzida para 5000 exemplos (seed=42)
11:42:25 | INFO     | Coluna de texto: text
11:42:25 | INFO     | Ground truth carregado da coluna 'label'
11:42:25 | INFO     | Textos: 5000
11:42:25 | INFO     | Categorias: [0, 1, 2, 3, 4]
11:42:25 | INFO     | Ground truth: Sim

### - Anotações

In [33]:
df_annotations = pd.read_csv(results_dataset_path.joinpath("annotations.csv"))

### - Métricas

In [34]:
df_metrics = pd.read_csv(results_dataset_path.joinpath("model_metrics.csv"))

df_metrics

,model,accuracy,f1_weighted,precision_weighted,recall_weighted,coverage,error_rate,invalid_predictions_rate
0,qwen3-8b,0.5144,0.493442,0.522000,0.5144,0.9998,0.4856,0.0002
1,deepseek-r1-8b,0.5114,0.490683,0.513325,0.5114,0.9986,0.4886,0.0014
2,gemma3-4b,0.5200,0.485635,0.518287,0.5200,0.9988,0.4800,0.0012
3,mistral-7b,0.4876,0.475012,0.496176,0.4876,1.0000,0.5124,0.0000
4,llama3.1-8b,0.4808,0.427891,0.512683,0.4808,0.9972,0.5192,0.0028

## 3) Calcular Consenso

In [35]:
from src.llm_annotation_system.consensus.consensus_calculator import ConsensusCalculator
from src.llm_annotation_system.consensus.consensus_evaluator import ConsensusEvaluator

# Inicializar calculador
consensus_calculator = ConsensusCalculator(
    consensus_threshold=consensus_threshold,
    default_strategy=consensus_strategy
)

analyzer = ConsensusEvaluator(
    categories=categories, 
    calculator=consensus_calculator, 
    output_dir=results_dataset_path
)

df_with_consensus = analyzer.compute_consensus(df_annotations)

11:42:25 | INFO     | Executando cálculo de consenso interno...
11:42:25 | INFO     | Calculando consenso...
11:42:25 | SUCCESS  | Consenso calculado:
11:42:25 | INFO     |   Alto (≥80%): 2999 (60.0%)
11:42:25 | INFO     |   Médio (60-80%): 1763 (35.3%)
11:42:25 | INFO     |   Baixo (<60%): 238 (4.8%)
11:42:25 | INFO     |   Problemáticos: 205 (4.1%)
11:42:25 | INFO     |   Itens que precisam de revisão: 0 (0.0%)
11:42:25 | SUCCESS  | Cálculo de consenso finalizado.

### - Estatisticas

In [36]:
logger.info("\n📊 Estatísticas de Consenso:")
logger.info(f"  Média: {df_with_consensus['consensus_score'].mean():.2%}")
logger.info(f"  Mediana: {df_with_consensus['consensus_score'].median():.2%}")
logger.info(f"  Desvio padrão: {df_with_consensus['consensus_score'].std():.2%}")

11:42:25 | INFO     |
📊 Estatísticas de Consenso:
11:42:25 | INFO     |   Média: 76.52%
11:42:25 | INFO     |   Mediana: 80.00%
11:42:25 | INFO     |   Desvio padrão: 17.74%

### - Distribuição por nível

In [37]:
# Distribuição por nível
levels = df_with_consensus['consensus_level'].value_counts()
logger.info("Distribuição por nível:")
for level, count in levels.items():
    logger.info(f"  {level}: {count} ({count/len(df_with_consensus):.1%})")

11:42:25 | INFO     | Distribuição por nível:
11:42:25 | INFO     |   high: 2999 (60.0%)
11:42:25 | INFO     |   medium: 1763 (35.3%)
11:42:25 | INFO     |   low: 238 (4.8%)

### - Visualizar consenso

In [38]:
from src.llm_annotation_system.consensus.consensus_visualizer import ConsensusVisualizer

visualizer = ConsensusVisualizer(output_dir=results_dataset_path)

In [39]:
visualizer.plot_score_and_levels(
    df_with_consensus=df_with_consensus,
    levels=levels
)

✓ Gráfico salvo: score_and_levels.html

## 4) Análise Detalhada de Consenso

### - Gerando Report

In [40]:
# Gerar relatório
report = analyzer.generate_consensus_report(
    df=df_with_consensus
)

logger.success("✓ Relatório gerado")

11:42:26 | INFO     | Gerando relatório completo de consenso...
11:42:26 | INFO     | Fleiss' Kappa: 0.480 (Moderado)
11:42:26 | INFO     | Casos problemáticos: 238
11:42:26 | SUCCESS  | Relatório de consenso gerado com sucesso.
11:42:26 | SUCCESS  | ✓ Relatório gerado

### - Pairwise_agreement

In [41]:
logger.info("\n📊 Gerando heatmap de concordância...")
visualizer.plot_agreement_heatmap(
    agreement_df=report['pairwise_agreement'],
    title='Matriz de Concordância entre Modelos',
)

11:42:26 | INFO     |
📊 Gerando heatmap de concordância...

✓ Heatmap salvo: agreement_heatmap.html

### - Cohens Kappa

In [42]:
logger.info("\n📊 Gerando heatmap de Cohens_Kappa...")
visualizer.plot_kappa_heatmap(
    kappa_df=report['cohens_kappa']
)

11:42:26 | INFO     |
📊 Gerando heatmap de Cohens_Kappa...

✓ Heatmap salvo: kappa_heatmap.html

### - Casos problemáticos

In [43]:
# Casos problemáticos
problematic = report.get('problematic_cases')
if problematic is not None and len(problematic) > 0:
    logger.warning(f"\n⚠️  {len(problematic)} casos problemáticos identificados")
    display(problematic)
else:
    logger.success("\n✓ Nenhum caso problemático identificado")

11:42:26 | WARNING  |
⚠️  238 casos problemáticos identificados

,text_id,text,consensus_score,annotations,entropy
0,2,some people want the ol' ball-and-chain and th...,0.4,"{1: 2, 2: 2, 3: 1}",1.521928
1,10,who is the audience for cletis tout ?\n,0.4,"{1: 1, 3: 1, 2: 2, 0: 1}",1.921928
2,35,but director danny devito and screenwriter ada...,0.4,"{1: 2, 3: 1, 2: 2}",1.521928
3,55,greg kinnear gives a mesmerizing performance a...,0.4,"{3: 1, 4: 2, 1: 2}",1.521928
4,107,an intriguing cinematic omnibus and round-robi...,0.4,"{3: 2, 2: 2, 1: 1}",1.521928
...,...,...,...,...,...
233,4863,"this sade is hardly a perverse , dangerous lib...",0.4,"{2: 2, 3: 2, 1: 1}",1.521928
234,4868,a tale of horror and revenge that is nearly pe...,0.4,"{0: 2, 3: 2, 1: 1}",1.521928
235,4948,his scenes are short and often unexpected .\n,0.4,"{1: 2, 3: 1, 2: 2}",1.521928
236,4951,"granddad of le nouvelle vague , jean-luc godar...",0.4,"{2: 2, 1: 1, 3: 2}",1.521928
237,4952,like leafing through an album of photos accomp...,0.4,"{2: 2, 1: 2, 3: 1}",1.521928

## 5) Validação com Ground Truth

In [44]:
accuracy, cls_report, cm = analyzer.evaluate_ground_truth(
    df_with_consensus=df_with_consensus
)

visualizer.plot_confusion_matrix(
    cm=cm,
    categories=categories
)

11:42:26 | SUCCESS  |
🎯 Accuracy: 53.78%
11:42:26 | INFO     |
Classification Report:
{'-1': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, '0': {'precision': 0.4849279161205767, 'recall': 0.578125, 'f1-score': 0.5274411974340698, 'support': 640.0}, '1': {'precision': 0.49191299498047963, 'recall': 0.6763803680981595, 'f1-score': 0.5695834678721343, 'support': 1304.0}, '2': {'precision': 0.5053003533568905, 'recall': 0.15132275132275133, 'f1-score': 0.23289902280130292, 'support': 945.0}, '3': {'precision': 0.572879330943847, 'recall': 0.719429857464366, 'f1-score': 0.6378450282673761, 'support': 1333.0}, '4': {'precision': 0.6950207468879668, 'recall': 0.4305912596401028, 'f1-score': 0.5317460317460317, 'support': 778.0}, 'accuracy': 0.5378, 'macro avg': {'precision': 0.4583402237149601, 'recall': 0.42597487275423, 'f1-score': 0.4165857913534858, 'support': 5000.0}, 'weighted avg': {'precision': 0.5467383069841926, 'recall': 0.5378, 'f1-score': 0.5128669240778247, 'support': 5000.0}}

c:\Users\gabri\Documents\GitHub\llm-annotation\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

c:\Users\gabri\Documents\GitHub\llm-annotation\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

c:\Users\gabri\Documents\GitHub\llm-annotation\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

✓ Matriz de confusão salva em: C:\Users\gabri\Documents\GitHub\llm-annotation\data\results\sst1\2026-01-19\graphics\confusion_matrix.html

## 6) Exportar Resultados

In [45]:
import json

# Criar diretório
results_dir = results_dataset_path.joinpath("summary")
results_dir.mkdir(parents=True, exist_ok=True)

# Salvar CSVs
df_with_consensus.to_csv(results_dir / 'dataset_anotado_completo.csv', index=False)
logger.info(f"✓ Salvos: {len(df_with_consensus)} registros")

# Alta confiança
high_conf = df_with_consensus[df_with_consensus['consensus_score'] >= 0.8]
high_conf.to_csv(results_dir / 'alta_confianca.csv', index=False)
logger.info(f"✓ Alta confiança: {len(high_conf)} registros")

# Necessita revisão
low_conf = df_with_consensus[df_with_consensus['consensus_score'] < 0.8]
low_conf.to_csv(results_dir / 'necessita_revisao.csv', index=False)
logger.info(f"✓ Necessita revisão: {len(low_conf)} registros")

# Sumário JSON
summary = {
    'dataset': {
        'name': dataset_name,
        'total_texts': len(texts),
        'categories': categories,
        'has_ground_truth': ground_truth is not None
    },
    'config': {
        'models': DEFAULT_MODELS,
        'total_models': len(DEFAULT_MODELS),
        'use_alternative_params': False,
        'num_repetitions': 1,
        'total_annotations': len(texts) * len(DEFAULT_MODELS) * 1
    },
    'results': {
        'consensus_mean': float(df_with_consensus['consensus_score'].mean()),
        'consensus_median': float(df_with_consensus['consensus_score'].median()),
        'high_consensus': int((df_with_consensus['consensus_level'] == 'high').sum()),
        'medium_consensus': int((df_with_consensus['consensus_level'] == 'medium').sum()),
        'low_consensus': int((df_with_consensus['consensus_level'] == 'low').sum()),
    },
    'metrics': {
        'fleiss_kappa': float(report['fleiss_kappa']),
        'fleiss_interpretation': report['fleiss_interpretation']
    }
}

if ground_truth:
    summary['validation'] = {
        'classification_report': cls_report
    }

with open(results_dir / 'sumario_experimento.json', 'w') as f:
    json.dump(summary, f, indent=2)

logger.success("\n✓ Resultados exportados com sucesso!")

11:42:26 | INFO     | ✓ Salvos: 5000 registros
11:42:26 | INFO     | ✓ Alta confiança: 2999 registros
11:42:26 | INFO     | ✓ Necessita revisão: 2001 registros
11:42:26 | SUCCESS  |
✓ Resultados exportados com sucesso!

## 10) Resumo Final

In [46]:
logger.info("\n" + "="*80)
logger.success("RESUMO DO EXPERIMENTO")
logger.info("="*80)

logger.info(f"\n📊 Dataset: {dataset_name}")
logger.info(f"  Textos: {len(texts)}")
logger.info(f"  Categorias: {len(categories)}")

logger.info(f"\n🤖 Configuração:")
logger.info(f"  Modelos base: {len(DEFAULT_MODELS)}")
logger.info(f"  Total modelos: {len(DEFAULT_MODELS)}")
logger.info(f"  Alternative params: {False}")
logger.info(f"  Repetições: {1}")

logger.info(f"\n📈 Consenso:")
logger.info(f"  Média: {df_with_consensus['consensus_score'].mean():.2%}")
logger.info(f"  Fleiss' Kappa: {report['fleiss_kappa']:.3f} ({report['fleiss_interpretation']})")

if ground_truth:
    logger.info(f"\n🎯 Validação:")
    logger.info(f"  Accuracy: {accuracy:.2%}")

logger.info(f"\n📁 Arquivos gerados em: {results_dir}/")

logger.success("\n✅ Análise completa!")

11:42:26 | INFO     |
================================================================================
11:42:26 | SUCCESS  | RESUMO DO EXPERIMENTO
11:42:26 | INFO     | ================================================================================
11:42:26 | INFO     |
📊 Dataset: sst1
11:42:26 | INFO     |   Textos: 5000
11:42:26 | INFO     |   Categorias: 5
11:42:26 | INFO     |
🤖 Configuração:
11:42:26 | INFO     |   Modelos base: 5
11:42:26 | INFO     |   Total modelos: 5
11:42:26 | INFO     |   Alternative params: False
11:42:26 | INFO     |   Repetições: 1
11:42:26 | INFO     |
📈 Consenso:
11:42:26 | INFO     |   Média: 76.52%
11:42:26 | INFO     |   Fleiss' Kappa: 0.480 (Moderado)
11:42:26 | INFO     |
🎯 Validação:
11:42:26 | INFO     |   Accuracy: 53.78%
11:42:26 | INFO     |
📁 Arquivos gerados em: C:\Users\gabri\Documents\GitHub\llm-annotation\data\results\sst1\2026-01-19\summary/
11:42:26 | SUCCESS  |
✅ Análise completa!