# 🔎 Análise de Consenso entre LLMs

## 1) Setup e Configuração

In [11]:
import sys
from loguru import logger
import pandas as pd
from src.api.schemas.experiment import ExperimentRequest

logger.remove()
logger.add(
    sys.stdout,
    format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>",
    level="INFO"
)

logger.success("✓ Setup completo")

00:16:53 | SUCCESS  | ✓ Setup completo

In [12]:
import json
from pathlib import Path

experiment = "large_experiment"

# Load JSON from file
config_path = Path(f"../experiments/{experiment}.json")

with open(config_path, "r") as f:
    config_dict = json.load(f)

# Instantiate Pydantic model
EXPERIMENT_CONFIG = ExperimentRequest(**config_dict)

### - Modelos e prompt

In [13]:
DEFAULT_MODELS = EXPERIMENT_CONFIG.models

PROMPT_TYPE = EXPERIMENT_CONFIG.prompt_type

### - Configurações de consenso

In [14]:
consensus_cfg = {
    "threshold": 0.8,
    "strategy": "majority_vote",
    "no_consensus_strategy": "flag_for_review",
}

consensus_threshold = consensus_cfg.get("threshold", 0.8)
consensus_strategy = consensus_cfg.get("strategy", "majority_vote")
no_consensus_strategy = consensus_cfg.get(
    "no_consensus_strategy", "flag_for_review"
)

### - Configurações de dataset

In [15]:
dataset_cfg = EXPERIMENT_CONFIG.dataset_config

dataset_split = dataset_cfg.split
combine_splits = dataset_cfg.combine_splits
sample_size = dataset_cfg.sample_size
random_state = dataset_cfg.random_state

### - Configurações de cache

In [16]:
cache_dir = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\.cache"

### - Resultados

In [17]:
results_dir = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\results"

In [18]:
from src.utils.get_latest_results_date import get_latest_results_date

dataset_name = "movie_review"  
specific_date = "latest"

if specific_date == "latest":
    specific_date = get_latest_results_date(
        results_dir,
        dataset_name
    )
    
results_dir = Path(results_dir)
results_dataset_path = results_dir.joinpath(dataset_name, specific_date)

## 2) Carregar dados

### - Dataset

In [19]:
from src.utils.data_loader import load_hf_dataset

texts, categories, ground_truth = load_hf_dataset(
    dataset_name=dataset_name, 
    cache_dir=cache_dir,
    dataset_global_config=dataset_cfg
)

logger.info(f"Textos: {len(texts)}")
logger.info(f"Categorias: {categories}")
logger.info(f"Ground truth: {'Sim' if ground_truth else 'Não'}")

00:16:53 | INFO     | Carregando dataset: movie_review
00:16:53 | INFO     | Baixando parquet direto do HuggingFace Hub
00:16:53 | INFO     | Arquivo baixado em: C:\Users\gabri\Documents\GitHub\llm-annotation\data\.cache\hf\datasets--waashk--movie_review\snapshots\caad4b8f3f59f863e490d10d00d8c36ebef40879\data.parquet
00:16:53 | INFO     | Dataset carregado: 10662 exemplos
00:16:53 | INFO     | Categorias extraídas automaticamente: [0, 1]
00:16:53 | INFO     | Dataset embaralhado com seed=42
00:16:53 | INFO     | Coluna de texto: text
00:16:53 | INFO     | Ground truth carregado da coluna 'label'
00:16:53 | INFO     | Textos: 10662
00:16:53 | INFO     | Categorias: [0, 1]
00:16:53 | INFO     | Ground truth: Sim

### - Anotações

In [20]:
df_annotations = pd.read_csv(results_dataset_path.joinpath("annotations.csv"))

### - Métricas

In [21]:
df_metrics = pd.read_csv(results_dataset_path.joinpath("model_metrics.csv"))

df_metrics

,model,accuracy,f1_macro,precision_macro,recall_macro,coverage,error_rate,invalid_predictions_rate
0,qwen3-8b,0.915025,0.915004,0.915448,0.915025,1.000000,0.084975,0.000000
1,deepseek-r1-8b,0.902832,0.603070,0.604409,0.601888,0.996061,0.097168,0.003939
2,llama3.1-8b,0.894298,0.596225,0.596279,0.596198,0.999906,0.105702,0.000094

## 3) Calcular Consenso

In [22]:
from src.llm_annotation_system.consensus.consensus_calculator import ConsensusCalculator
from src.llm_annotation_system.consensus.consensus_evaluator import ConsensusEvaluator

# Inicializar calculador
consensus_calculator = ConsensusCalculator(
    consensus_threshold=consensus_threshold,
    default_strategy=consensus_strategy
)

analyzer = ConsensusEvaluator(
    categories=categories, 
    calculator=consensus_calculator, 
    output_dir=results_dataset_path
)

df_with_consensus = analyzer.compute_consensus(df_annotations)

00:16:54 | INFO     | Executando cálculo de consenso interno...
00:16:54 | INFO     | Calculando consenso...
00:16:54 | SUCCESS  | Consenso calculado:
00:16:54 | INFO     |   Alto (≥80%): 9577 (89.8%)
00:16:54 | INFO     |   Médio (60-80%): 1077 (10.1%)
00:16:54 | INFO     |   Baixo (<60%): 8 (0.1%)
00:16:54 | INFO     |   Problemáticos: 8 (0.1%)
00:16:54 | INFO     |   Itens que precisam de revisão: 0 (0.0%)
00:16:54 | SUCCESS  | Cálculo de consenso finalizado.

### - Estatisticas

In [23]:
logger.info("\n📊 Estatísticas de Consenso:")
logger.info(f"  Média: {df_with_consensus['consensus_score'].mean():.2%}")
logger.info(f"  Mediana: {df_with_consensus['consensus_score'].median():.2%}")
logger.info(f"  Desvio padrão: {df_with_consensus['consensus_score'].std():.2%}")

00:16:54 | INFO     |
📊 Estatísticas de Consenso:
00:16:54 | INFO     |   Média: 96.58%
00:16:54 | INFO     |   Mediana: 100.00%
00:16:54 | INFO     |   Desvio padrão: 10.19%

### - Distribuição por nível

In [24]:
# Distribuição por nível
levels = df_with_consensus['consensus_level'].value_counts()
logger.info("Distribuição por nível:")
for level, count in levels.items():
    logger.info(f"  {level}: {count} ({count/len(df_with_consensus):.1%})")

00:16:54 | INFO     | Distribuição por nível:
00:16:54 | INFO     |   high: 9577 (89.8%)
00:16:54 | INFO     |   medium: 1077 (10.1%)
00:16:54 | INFO     |   low: 8 (0.1%)

### - Visualizar consenso

In [25]:
from src.llm_annotation_system.consensus.consensus_visualizer import ConsensusVisualizer

visualizer = ConsensusVisualizer(output_dir=results_dataset_path)

In [26]:
visualizer.plot_score_and_levels(
    df_with_consensus=df_with_consensus,
    levels=levels
)

✓ Gráfico salvo: score_and_levels.html

## 4) Análise Detalhada de Consenso

### - Gerando Report

In [27]:
# Gerar relatório
report = analyzer.generate_consensus_report(
    df=df_with_consensus
)

logger.success("✓ Relatório gerado")

00:16:56 | INFO     | Gerando relatório completo de consenso...
00:16:56 | INFO     | Fleiss' Kappa: 0.863 (Excelente)
00:16:57 | INFO     | Casos problemáticos: 8
00:16:57 | SUCCESS  | Relatório de consenso gerado com sucesso.
00:16:57 | SUCCESS  | ✓ Relatório gerado

### - Pairwise_agreement

In [28]:
logger.info("\n📊 Gerando heatmap de concordância...")
visualizer.plot_agreement_heatmap(
    agreement_df=report['pairwise_agreement'],
    title='Matriz de Concordância entre Modelos',
)

00:16:57 | INFO     |
📊 Gerando heatmap de concordância...

✓ Heatmap salvo: agreement_heatmap.html

### - Cohens Kappa

In [29]:
logger.info("\n📊 Gerando heatmap de Cohens_Kappa...")
visualizer.plot_kappa_heatmap(
    kappa_df=report['cohens_kappa']
)

00:16:57 | INFO     |
📊 Gerando heatmap de Cohens_Kappa...

✓ Heatmap salvo: kappa_heatmap.html

### - Casos problemáticos

In [30]:
# Casos problemáticos
problematic = report.get('problematic_cases')
if problematic is not None and len(problematic) > 0:
    logger.warning(f"\n⚠️  {len(problematic)} casos problemáticos identificados")
    display(problematic)
else:
    logger.success("\n✓ Nenhum caso problemático identificado")

00:16:57 | WARNING  |
⚠️  8 casos problemáticos identificados

,text_id,text,consensus_score,annotations,entropy
0,5910e6e9c8585acbf48f93e966c134f8,[a] slummer .\n,0.333333,"{-1: 1, 0: 1, 1: 1}",1.584963
1,f9024dd5886b1e69f75755a2a5c8f6e3,maybe thomas wolfe was right : you can't go ho...,0.333333,"{-1: 1, 0: 1, 1: 1}",1.584963
2,37829ba9e0b990399501a6c9e9daec93,adam sandler ! in an art film !\n,0.333333,"{-1: 1, 0: 1, 1: 1}",1.584963
3,1b0af1a75d1d9cc7e8873effbb3895bf,is there enough material to merit a documentar...,0.333333,"{-1: 1, 0: 1, 1: 1}",1.584963
4,d7023826ff3e5374b87c2c5e1685df98,what's next ? the porky's revenge : ultimate e...,0.333333,"{-1: 1, 0: 1, 1: 1}",1.584963
5,57ad71280ced9c96e474202b44d277d7,"what's next : "" my mother the car ? ""\n",0.333333,"{-1: 1, 0: 1, 1: 1}",1.584963
6,dfa8d3456f88102b3cb726aa3cdc3e48,el ttulo no engaa : la pelcula narra una histo...,0.333333,"{-1: 1, 1: 1, 0: 1}",1.584963
7,5c8b6ff01caa23e26715640ee60948c9,for dance completists only .\n,0.333333,"{-1: 1, 0: 1, 1: 1}",1.584963

## 5) Validação com Ground Truth

In [31]:
accuracy, cls_report, cm = analyzer.evaluate_ground_truth(
    df_with_consensus=df_with_consensus
)

visualizer.plot_confusion_matrix(
    cm=cm,
    categories=categories
)

00:16:57 | SUCCESS  |
🎯 Accuracy: 91.28%
00:16:57 | INFO     |
Classification Report:
{'-1': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, '0': {'precision': 0.9038884812912693, 'recall': 0.9244044269367848, 'f1-score': 0.9140313456366502, 'support': 5331.0}, '1': {'precision': 0.9236685252835993, 'recall': 0.9011442506096418, 'f1-score': 0.9122673756171668, 'support': 5331.0}, 'accuracy': 0.9127743387732132, 'macro avg': {'precision': 0.6091856688582896, 'recall': 0.6085162258488088, 'f1-score': 0.608766240417939, 'support': 10662.0}, 'weighted avg': {'precision': 0.9137785032874345, 'recall': 0.9127743387732132, 'f1-score': 0.9131493606269085, 'support': 10662.0}}

c:\Users\gabri\Documents\GitHub\llm-annotation\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

c:\Users\gabri\Documents\GitHub\llm-annotation\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

c:\Users\gabri\Documents\GitHub\llm-annotation\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

✓ Matriz de confusão salva em: C:\Users\gabri\Documents\GitHub\llm-annotation\data\results\movie_review\2026-03-22_14-49-24\graphics\confusion_matrix.html

## 6) Exportar Resultados

In [32]:
import json

# Criar diretório
results_dir = results_dataset_path.joinpath("summary")
results_dir.mkdir(parents=True, exist_ok=True)

# Salvar CSVs
df_with_consensus.to_csv(results_dir / 'dataset_anotado_completo.csv', index=False)
logger.info(f"✓ Salvos: {len(df_with_consensus)} registros")

# Alta confiança
high_conf = df_with_consensus[df_with_consensus['consensus_score'] >= 0.8]
high_conf.to_csv(results_dir / 'alta_confianca.csv', index=False)
logger.info(f"✓ Alta confiança: {len(high_conf)} registros")

# Necessita revisão
low_conf = df_with_consensus[df_with_consensus['consensus_score'] < 0.8]
low_conf.to_csv(results_dir / 'necessita_revisao.csv', index=False)
logger.info(f"✓ Necessita revisão: {len(low_conf)} registros")

# Sumário JSON
summary = {
    'dataset': {
        'name': dataset_name,
        'total_texts': len(texts),
        'categories': categories,
        'has_ground_truth': ground_truth is not None
    },
    'config': {
        'models': DEFAULT_MODELS,
        'prompt_type': PROMPT_TYPE,
        'total_models': len(DEFAULT_MODELS),
        'use_alternative_params': False,
        'num_repetitions': 1,
        'total_annotations': len(texts) * len(DEFAULT_MODELS) * 1
    },
    'results': {
        'consensus_mean': float(df_with_consensus['consensus_score'].mean()),
        'consensus_median': float(df_with_consensus['consensus_score'].median()),
        'high_consensus': int((df_with_consensus['consensus_level'] == 'high').sum()),
        'medium_consensus': int((df_with_consensus['consensus_level'] == 'medium').sum()),
        'low_consensus': int((df_with_consensus['consensus_level'] == 'low').sum()),
    },
    'metrics': {
        'fleiss_kappa': float(report['fleiss_kappa']),
        'fleiss_interpretation': report['fleiss_interpretation']
    }
}

if ground_truth:
    summary['validation'] = {
        'classification_report': cls_report
    }

with open(results_dir / 'sumario_experimento.json', 'w') as f:
    json.dump(summary, f, indent=2)

logger.success("\n✓ Resultados exportados com sucesso!")

00:16:57 | INFO     | ✓ Salvos: 10662 registros
00:16:57 | INFO     | ✓ Alta confiança: 9577 registros
00:16:57 | INFO     | ✓ Necessita revisão: 1085 registros
00:16:57 | SUCCESS  |
✓ Resultados exportados com sucesso!

## 10) Resumo Final

In [33]:
logger.info("\n" + "="*80)
logger.success("RESUMO DO EXPERIMENTO")
logger.info("="*80)

logger.info(f"\n📊 Dataset: {dataset_name}")
logger.info(f"  Textos: {len(texts)}")
logger.info(f"  Categorias: {len(categories)}")

logger.info(f"\n🤖 Configuração:")
logger.info(f"  Modelos base: {len(DEFAULT_MODELS)}")
logger.info(f"  Total modelos: {len(DEFAULT_MODELS)}")
logger.info(f"  Alternative params: {False}")
logger.info(f"  Repetições: {1}")

logger.info(f"\n📈 Consenso:")
logger.info(f"  Média: {df_with_consensus['consensus_score'].mean():.2%}")
logger.info(f"  Fleiss' Kappa: {report['fleiss_kappa']:.3f} ({report['fleiss_interpretation']})")

if ground_truth:
    logger.info(f"\n🎯 Validação:")
    logger.info(f"  Accuracy: {accuracy:.2%}")

logger.info(f"\n📁 Arquivos gerados em: {results_dir}/")

logger.success("\n✅ Análise completa!")

00:16:57 | INFO     |
================================================================================
00:16:57 | SUCCESS  | RESUMO DO EXPERIMENTO
00:16:57 | INFO     | ================================================================================
00:16:57 | INFO     |
📊 Dataset: movie_review
00:16:57 | INFO     |   Textos: 10662
00:16:57 | INFO     |   Categorias: 2
00:16:57 | INFO     |
🤖 Configuração:
00:16:57 | INFO     |   Modelos base: 3
00:16:57 | INFO     |   Total modelos: 3
00:16:57 | INFO     |   Alternative params: False
00:16:57 | INFO     |   Repetições: 1
00:16:57 | INFO     |
📈 Consenso:
00:16:57 | INFO     |   Média: 96.58%
00:16:57 | INFO     |   Fleiss' Kappa: 0.863 (Excelente)
00:16:57 | INFO     |
🎯 Validação:
00:16:57 | INFO     |   Accuracy: 91.28%
00:16:57 | INFO     |
📁 Arquivos gerados em: C:\Users\gabri\Documents\GitHub\llm-annotation\data\results\movie_review\2026-03-22_14-49-24\summary/
00:16:57 | SUCCESS  |
✅ Análise completa!