# 🔎 Análise de Consenso entre LLMs

## 1) Setup e Configuração

In [25]:
import sys
from loguru import logger
import pandas as pd
from src.api.schemas.experiment import ExperimentRequest

logger.remove()
logger.add(
    sys.stdout,
    format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>",
    level="INFO"
)

logger.success("✓ Setup completo")

12:38:09 | SUCCESS  | ✓ Setup completo

In [26]:
import json
from pathlib import Path

experiment = "experiment_3_models"

# Load JSON from file
config_path = Path(f"../experiments/{experiment}.json")

with open(config_path, "r") as f:
    config_dict = json.load(f)

# Instantiate Pydantic model
EXPERIMENT_CONFIG = ExperimentRequest(**config_dict)

### - Modelos e prompt

In [27]:
DEFAULT_MODELS = EXPERIMENT_CONFIG.models

PROMPT_TYPE = EXPERIMENT_CONFIG.prompt_type

### - Configurações de consenso

In [28]:
consensus_cfg = {
    "threshold": 0.8,
    "strategy": "majority_vote",
    "no_consensus_strategy": "flag_for_review",
}

consensus_threshold = consensus_cfg.get("threshold", 0.8)
consensus_strategy = consensus_cfg.get("strategy", "majority_vote")
no_consensus_strategy = consensus_cfg.get(
    "no_consensus_strategy", "flag_for_review"
)

### - Configurações de dataset

In [29]:
dataset_cfg = EXPERIMENT_CONFIG.dataset_config

dataset_split = dataset_cfg.split
combine_splits = dataset_cfg.combine_splits
sample_size = dataset_cfg.sample_size
random_state = dataset_cfg.random_state

### - Configurações de cache

In [30]:
cache_dir = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\.cache"

### - Resultados

In [31]:
results_dir = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\results"

In [32]:
from src.utils.get_latest_results_date import get_latest_results_date

dataset_name = "movie_review"  
specific_date = "latest"

if specific_date == "latest":
    specific_date = get_latest_results_date(
        results_dir,
        dataset_name
    )
    
results_dir = Path(results_dir)
results_dataset_path = results_dir.joinpath(dataset_name, specific_date)

## 2) Carregar dados

### - Dataset

In [33]:
from src.utils.data_loader import load_hf_dataset

texts, categories, ground_truth = load_hf_dataset(
    dataset_name=dataset_name, 
    cache_dir=cache_dir,
    dataset_global_config=dataset_cfg
)

logger.info(f"Textos: {len(texts)}")
logger.info(f"Categorias: {categories}")
logger.info(f"Ground truth: {'Sim' if ground_truth else 'Não'}")

12:38:09 | INFO     | Carregando dataset: movie_review
12:38:16 | INFO     | Split 'train': 95958 exemplos
12:38:16 | INFO     | Categorias extraídas automaticamente: [0, 1]
12:38:16 | INFO     | Amostra reduzida para 5000 exemplos (seed=42)
12:38:16 | INFO     | Coluna de texto: text
12:38:16 | INFO     | Ground truth carregado da coluna 'label'
12:38:16 | INFO     | Textos: 5000
12:38:16 | INFO     | Categorias: [0, 1]
12:38:16 | INFO     | Ground truth: Sim

### - Anotações

In [34]:
df_annotations = pd.read_csv(results_dataset_path.joinpath("annotations.csv"))

### - Métricas

In [35]:
df_metrics = pd.read_csv(results_dataset_path.joinpath("model_metrics.csv"))

df_metrics

,model,accuracy,f1_weighted,precision_weighted,recall_weighted,coverage,error_rate,invalid_predictions_rate
0,qwen3-8b,0.9176,0.917559,0.918012,0.9176,1.000,0.0824,0.000
1,deepseek-r1-8b,0.9062,0.907069,0.908250,0.9062,0.998,0.0938,0.002
2,llama3.1-8b,0.8948,0.894801,0.894803,0.8948,1.000,0.1052,0.000

## 3) Calcular Consenso

In [36]:
from src.llm_annotation_system.consensus.consensus_calculator import ConsensusCalculator
from src.llm_annotation_system.consensus.consensus_evaluator import ConsensusEvaluator

# Inicializar calculador
consensus_calculator = ConsensusCalculator(
    consensus_threshold=consensus_threshold,
    default_strategy=consensus_strategy
)

analyzer = ConsensusEvaluator(
    categories=categories, 
    calculator=consensus_calculator, 
    output_dir=results_dataset_path
)

df_with_consensus = analyzer.compute_consensus(df_annotations)

12:38:16 | INFO     | Executando cálculo de consenso interno...
12:38:16 | INFO     | Calculando consenso...
12:38:16 | SUCCESS  | Consenso calculado:
12:38:16 | INFO     |   Alto (≥80%): 4472 (89.4%)
12:38:16 | INFO     |   Médio (60-80%): 526 (10.5%)
12:38:16 | INFO     |   Baixo (<60%): 2 (0.0%)
12:38:16 | INFO     |   Problemáticos: 2 (0.0%)
12:38:16 | INFO     |   Itens que precisam de revisão: 0 (0.0%)
12:38:16 | SUCCESS  | Cálculo de consenso finalizado.

### - Estatisticas

In [37]:
logger.info("\n📊 Estatísticas de Consenso:")
logger.info(f"  Média: {df_with_consensus['consensus_score'].mean():.2%}")
logger.info(f"  Mediana: {df_with_consensus['consensus_score'].median():.2%}")
logger.info(f"  Desvio padrão: {df_with_consensus['consensus_score'].std():.2%}")

12:38:16 | INFO     |
📊 Estatísticas de Consenso:
12:38:16 | INFO     |   Média: 96.47%
12:38:16 | INFO     |   Mediana: 100.00%
12:38:16 | INFO     |   Desvio padrão: 10.31%

### - Distribuição por nível

In [38]:
# Distribuição por nível
levels = df_with_consensus['consensus_level'].value_counts()
logger.info("Distribuição por nível:")
for level, count in levels.items():
    logger.info(f"  {level}: {count} ({count/len(df_with_consensus):.1%})")

12:38:16 | INFO     | Distribuição por nível:
12:38:16 | INFO     |   high: 4472 (89.4%)
12:38:16 | INFO     |   medium: 526 (10.5%)
12:38:16 | INFO     |   low: 2 (0.0%)

### - Visualizar consenso

In [39]:
from src.llm_annotation_system.consensus.consensus_visualizer import ConsensusVisualizer

visualizer = ConsensusVisualizer(output_dir=results_dataset_path)

In [40]:
visualizer.plot_score_and_levels(
    df_with_consensus=df_with_consensus,
    levels=levels
)

✓ Gráfico salvo: score_and_levels.html

## 4) Análise Detalhada de Consenso

### - Gerando Report

In [41]:
# Gerar relatório
report = analyzer.generate_consensus_report(
    df=df_with_consensus
)

logger.success("✓ Relatório gerado")

12:38:16 | INFO     | Gerando relatório completo de consenso...
12:38:16 | INFO     | Fleiss' Kappa: 0.858 (Excelente)
12:38:16 | INFO     | Casos problemáticos: 2
12:38:16 | SUCCESS  | Relatório de consenso gerado com sucesso.
12:38:16 | SUCCESS  | ✓ Relatório gerado

### - Pairwise_agreement

In [42]:
logger.info("\n📊 Gerando heatmap de concordância...")
visualizer.plot_agreement_heatmap(
    agreement_df=report['pairwise_agreement'],
    title='Matriz de Concordância entre Modelos',
)

12:38:16 | INFO     |
📊 Gerando heatmap de concordância...

✓ Heatmap salvo: agreement_heatmap.html

### - Cohens Kappa

In [43]:
logger.info("\n📊 Gerando heatmap de Cohens_Kappa...")
visualizer.plot_kappa_heatmap(
    kappa_df=report['cohens_kappa']
)

12:38:16 | INFO     |
📊 Gerando heatmap de Cohens_Kappa...

✓ Heatmap salvo: kappa_heatmap.html

### - Casos problemáticos

In [44]:
# Casos problemáticos
problematic = report.get('problematic_cases')
if problematic is not None and len(problematic) > 0:
    logger.warning(f"\n⚠️  {len(problematic)} casos problemáticos identificados")
    display(problematic)
else:
    logger.success("\n✓ Nenhum caso problemático identificado")

12:38:16 | WARNING  |
⚠️  2 casos problemáticos identificados

,text_id,text,consensus_score,annotations,entropy
0,578,a real story about real people living their li...,0.333333,"{-1: 1, 1: 1, 0: 1}",1.584963
1,4185,"what's next : "" my mother the car ? ""\n",0.333333,"{-1: 1, 0: 1, 1: 1}",1.584963

## 5) Validação com Ground Truth

In [45]:
accuracy, cls_report, cm = analyzer.evaluate_ground_truth(
    df_with_consensus=df_with_consensus
)

visualizer.plot_confusion_matrix(
    cm=cm,
    categories=categories
)

12:38:16 | SUCCESS  |
🎯 Accuracy: 91.38%
12:38:16 | INFO     |
Classification Report:
{'-1': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 0.0}, '0': {'precision': 0.90715667311412, 'recall': 0.9250493096646942, 'f1-score': 0.916015625, 'support': 2535.0}, '1': {'precision': 0.9216742644011604, 'recall': 0.9022312373225152, 'f1-score': 0.9118491184911849, 'support': 2465.0}, 'accuracy': 0.9138, 'macro avg': {'precision': 0.6096103125050935, 'recall': 0.6090935156624031, 'f1-score': 0.609288247830395, 'support': 5000.0}, 'weighted avg': {'precision': 0.9143138456186308, 'recall': 0.9138, 'f1-score': 0.9139615372911541, 'support': 5000.0}}

c:\Users\gabri\Documents\GitHub\llm-annotation\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

c:\Users\gabri\Documents\GitHub\llm-annotation\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

c:\Users\gabri\Documents\GitHub\llm-annotation\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning:

Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

✓ Matriz de confusão salva em: C:\Users\gabri\Documents\GitHub\llm-annotation\data\results\movie_review\2026-03-03\graphics\confusion_matrix.html

## 6) Exportar Resultados

In [46]:
import json

# Criar diretório
results_dir = results_dataset_path.joinpath("summary")
results_dir.mkdir(parents=True, exist_ok=True)

# Salvar CSVs
df_with_consensus.to_csv(results_dir / 'dataset_anotado_completo.csv', index=False)
logger.info(f"✓ Salvos: {len(df_with_consensus)} registros")

# Alta confiança
high_conf = df_with_consensus[df_with_consensus['consensus_score'] >= 0.8]
high_conf.to_csv(results_dir / 'alta_confianca.csv', index=False)
logger.info(f"✓ Alta confiança: {len(high_conf)} registros")

# Necessita revisão
low_conf = df_with_consensus[df_with_consensus['consensus_score'] < 0.8]
low_conf.to_csv(results_dir / 'necessita_revisao.csv', index=False)
logger.info(f"✓ Necessita revisão: {len(low_conf)} registros")

# Sumário JSON
summary = {
    'dataset': {
        'name': dataset_name,
        'total_texts': len(texts),
        'categories': categories,
        'has_ground_truth': ground_truth is not None
    },
    'config': {
        'models': DEFAULT_MODELS,
        'prompt_type': PROMPT_TYPE,
        'total_models': len(DEFAULT_MODELS),
        'use_alternative_params': False,
        'num_repetitions': 1,
        'total_annotations': len(texts) * len(DEFAULT_MODELS) * 1
    },
    'results': {
        'consensus_mean': float(df_with_consensus['consensus_score'].mean()),
        'consensus_median': float(df_with_consensus['consensus_score'].median()),
        'high_consensus': int((df_with_consensus['consensus_level'] == 'high').sum()),
        'medium_consensus': int((df_with_consensus['consensus_level'] == 'medium').sum()),
        'low_consensus': int((df_with_consensus['consensus_level'] == 'low').sum()),
    },
    'metrics': {
        'fleiss_kappa': float(report['fleiss_kappa']),
        'fleiss_interpretation': report['fleiss_interpretation']
    }
}

if ground_truth:
    summary['validation'] = {
        'classification_report': cls_report
    }

with open(results_dir / 'sumario_experimento.json', 'w') as f:
    json.dump(summary, f, indent=2)

logger.success("\n✓ Resultados exportados com sucesso!")

12:38:17 | INFO     | ✓ Salvos: 5000 registros
12:38:17 | INFO     | ✓ Alta confiança: 4472 registros
12:38:17 | INFO     | ✓ Necessita revisão: 528 registros
12:38:17 | SUCCESS  |
✓ Resultados exportados com sucesso!

## 10) Resumo Final

In [47]:
logger.info("\n" + "="*80)
logger.success("RESUMO DO EXPERIMENTO")
logger.info("="*80)

logger.info(f"\n📊 Dataset: {dataset_name}")
logger.info(f"  Textos: {len(texts)}")
logger.info(f"  Categorias: {len(categories)}")

logger.info(f"\n🤖 Configuração:")
logger.info(f"  Modelos base: {len(DEFAULT_MODELS)}")
logger.info(f"  Total modelos: {len(DEFAULT_MODELS)}")
logger.info(f"  Alternative params: {False}")
logger.info(f"  Repetições: {1}")

logger.info(f"\n📈 Consenso:")
logger.info(f"  Média: {df_with_consensus['consensus_score'].mean():.2%}")
logger.info(f"  Fleiss' Kappa: {report['fleiss_kappa']:.3f} ({report['fleiss_interpretation']})")

if ground_truth:
    logger.info(f"\n🎯 Validação:")
    logger.info(f"  Accuracy: {accuracy:.2%}")

logger.info(f"\n📁 Arquivos gerados em: {results_dir}/")

logger.success("\n✅ Análise completa!")

12:38:17 | INFO     |
================================================================================
12:38:17 | SUCCESS  | RESUMO DO EXPERIMENTO
12:38:17 | INFO     | ================================================================================
12:38:17 | INFO     |
📊 Dataset: movie_review
12:38:17 | INFO     |   Textos: 5000
12:38:17 | INFO     |   Categorias: 2
12:38:17 | INFO     |
🤖 Configuração:
12:38:17 | INFO     |   Modelos base: 3
12:38:17 | INFO     |   Total modelos: 3
12:38:17 | INFO     |   Alternative params: False
12:38:17 | INFO     |   Repetições: 1
12:38:17 | INFO     |
📈 Consenso:
12:38:17 | INFO     |   Média: 96.47%
12:38:17 | INFO     |   Fleiss' Kappa: 0.858 (Excelente)
12:38:17 | INFO     |
🎯 Validação:
12:38:17 | INFO     |   Accuracy: 91.38%
12:38:17 | INFO     |
📁 Arquivos gerados em: C:\Users\gabri\Documents\GitHub\llm-annotation\data\results\movie_review\2026-03-03\summary/
12:38:17 | SUCCESS  |
✅ Análise completa!