# Fine-tuning controlado de RoBERTa (GT vs Consenso LLM)

## 1) Imports e setup

In [18]:
import pandas as pd
from transformers import TrainingArguments
from datasets import Dataset
from pathlib import Path

import sys
from loguru import logger
import pandas as pd

logger.remove()
logger.add(
    sys.stdout,
    format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>",
    level="INFO"
)

logger.success("✓ Setup completo")

# loaders
from src.utils.data_loader import load_hf_dataset_as_dataframe

# fine-tuning system
from src.fine_tune_system.fine_tune.supervised_fine_tuner import SupervisedFineTuner
from src.fine_tune_system.core.hf_tokenizer import HFTokenizer
from src.fine_tune_system.core.model_factory import ModelFactory
from src.fine_tune_system.training.trainer_builder import TrainerBuilder
from src.fine_tune_system.training.metrics import MetricsComputer
from src.fine_tune_system.training.label_schema import LabelSchema
from src.utils.dataset_aligner import DatasetAligner

14:03:01 | SUCCESS  | ✓ Setup completo

## 2) Configuração do experimento

### - Configurações de dataset

In [19]:
from src.api.schemas.dataset import DatasetConfig

DATASET_GLOBAL_CONFIG_TRAIN = DatasetConfig(
    split="train",
    combine_splits=[],
    sample_size=None,
    random_state=42,
)

DATASET_GLOBAL_CONFIG_EVAL = DatasetConfig(
    split="test",
    combine_splits=[],
    sample_size=5000,
    random_state=42,
)

### - Configurações de cache

In [20]:
CACHE_ENABLED = True
CACHE_DIR = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\.cache"

### - Resultados

In [21]:
RESULTS_DIR = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\results"

In [22]:
from src.utils.get_latest_results_date import get_latest_results_date

DATASET_NAME = "dblp"  
specific_date = "latest"

if specific_date == "latest":
    specific_date = get_latest_results_date(
        RESULTS_DIR,
        DATASET_NAME
    )
    
RESULTS_DIR = Path(RESULTS_DIR)
results_dataset_path = RESULTS_DIR.joinpath(DATASET_NAME, specific_date)

## 3) Carregar Dados

### - Carregando

In [23]:
df = pd.read_csv(results_dataset_path.joinpath("summary", "dataset_anotado_completo.csv"))

print(f"Anotado: {len(df)}")

Anotado: 37385

### - Dataset ground_truth

In [24]:
df_gt_train = (
    df[["text_id", "text", "ground_truth"]]
    .rename(columns={"ground_truth": "label"})
)

In [25]:
# Quantas duplicatas existem
num_duplicadas = df_gt_train.duplicated(subset=["text_id"]).sum()
print(f"Duplicatas encontradas: {num_duplicadas}")

# Ver exemplos
duplicadas = df_gt_train[df_gt_train.duplicated(subset=["text_id"], keep=False)]
duplicadas.sort_values("text")

Duplicatas encontradas: 147

,text_id,text,label
14273,89d7fdd5d29c1e7be1743f5f535405e7,a faster and simpler fully dynamic transitive ...,9
14272,89d7fdd5d29c1e7be1743f5f535405e7,a faster and simpler fully dynamic transitive ...,9
4235,89d7fdd5d29c1e7be1743f5f535405e7,a faster and simpler fully dynamic transitive ...,9
4236,89d7fdd5d29c1e7be1743f5f535405e7,a faster and simpler fully dynamic transitive ...,9
17670,f7bcd53bdbf4021684067e7a517eb7f5,a global geometric approach for image clusteri...,0
...,...,...,...
13644,da3ef6f9e35fcb0b8d8d1fc8709a607e,"towards personal mt: general design, dialogue ...",1
13785,da3ef6f9e35fcb0b8d8d1fc8709a607e,"towards personal mt: general design, dialogue ...",1
13786,da3ef6f9e35fcb0b8d8d1fc8709a607e,"towards personal mt: general design, dialogue ...",1
1857,b751f05d496b0d382be68d42624113e0,two-hand gesture recognition using coupled swi...,0
1856,b751f05d496b0d382be68d42624113e0,two-hand gesture recognition using coupled swi...,0

In [ ]:
from src.utils.data_loader import add_label_description

df_gt_train = add_label_description(
    df_gt_train,
    dataset_name=DATASET_NAME
)

In [ ]:
label_schema = LabelSchema.from_dataframe(df_gt_train)
print(label_schema.id2label)

{0: 'negative sentiment', 1: 'positive sentiment'}

In [ ]:
df_gt_train

,text_id,text,label,label_description
0,6de239969386800ffdf0242777786c25,a comprehensive and provocative film -- one th...,1,positive sentiment
1,27a36737f5398d6716d230af108dfc0c,"perhaps the grossest movie ever made . funny ,...",1,positive sentiment
2,291c460bf5ce5ca42eb82c8946407e0b,the overall effect is awe and affection -- and...,1,positive sentiment
3,f806339daa6d03eb17716fcec63e6946,you have to pay attention to follow all the st...,1,positive sentiment
4,b061becd1af422a7a06f840b8cb75072,"the movie is genial but never inspired , and l...",0,negative sentiment
...,...,...,...,...
10657,63d4880669f1831d8e2e06e146a5d362,"it's a drawling , slobbering , lovable run-on ...",1,positive sentiment
10658,b505ee0f7dcbe4a8ceabd5d81d95327d,if the message seems more facile than the earl...,1,positive sentiment
10659,3cb36356e338ef8387506ab68c84d5d0,i approached the usher and said that if she ha...,0,negative sentiment
10660,db69ef73c623fc39a04e8cac58292439,it's the unsettling images of a war-ravaged la...,1,positive sentiment
10661,f03049887fcce98a8992d1faaefb931f,my thoughts were focused on the characters . t...,1,positive sentiment

### - Dataset anotado

In [ ]:
df_annotations = (
    df[["text_id", "text", "resolved_annotation"]]
    .rename(columns={"resolved_annotation": "label"})
)

In [ ]:
df_annotations = add_label_description(
    df_annotations,
    dataset_name=DATASET_NAME
)

In [ ]:
df_annotations

,text_id,text,label,label_description
0,6de239969386800ffdf0242777786c25,a comprehensive and provocative film -- one th...,1,positive sentiment
1,27a36737f5398d6716d230af108dfc0c,"perhaps the grossest movie ever made . funny ,...",0,negative sentiment
2,291c460bf5ce5ca42eb82c8946407e0b,the overall effect is awe and affection -- and...,1,positive sentiment
3,f806339daa6d03eb17716fcec63e6946,you have to pay attention to follow all the st...,1,positive sentiment
4,b061becd1af422a7a06f840b8cb75072,"the movie is genial but never inspired , and l...",0,negative sentiment
...,...,...,...,...
10657,63d4880669f1831d8e2e06e146a5d362,"it's a drawling , slobbering , lovable run-on ...",1,positive sentiment
10658,b505ee0f7dcbe4a8ceabd5d81d95327d,if the message seems more facile than the earl...,0,negative sentiment
10659,3cb36356e338ef8387506ab68c84d5d0,i approached the usher and said that if she ha...,0,negative sentiment
10660,db69ef73c623fc39a04e8cac58292439,it's the unsettling images of a war-ravaged la...,1,positive sentiment
10661,f03049887fcce98a8992d1faaefb931f,my thoughts were focused on the characters . t...,1,positive sentiment

### - Removendo instancias problemáticas e invalidas

#### -> Invalidas

##### Removendo do Ground-Truth

In [ ]:
df_invalid_gt = df_gt_train.loc[
    df_gt_train["label"] == -1 
]

df_gt_train = df_gt_train[
        ~df_gt_train["text_id"].isin(df_invalid_gt["text_id"])
    ].reset_index(drop=True)

In [ ]:
df_gt_train

,text_id,text,label,label_description
0,6de239969386800ffdf0242777786c25,a comprehensive and provocative film -- one th...,1,positive sentiment
1,27a36737f5398d6716d230af108dfc0c,"perhaps the grossest movie ever made . funny ,...",1,positive sentiment
2,291c460bf5ce5ca42eb82c8946407e0b,the overall effect is awe and affection -- and...,1,positive sentiment
3,f806339daa6d03eb17716fcec63e6946,you have to pay attention to follow all the st...,1,positive sentiment
4,b061becd1af422a7a06f840b8cb75072,"the movie is genial but never inspired , and l...",0,negative sentiment
...,...,...,...,...
10657,63d4880669f1831d8e2e06e146a5d362,"it's a drawling , slobbering , lovable run-on ...",1,positive sentiment
10658,b505ee0f7dcbe4a8ceabd5d81d95327d,if the message seems more facile than the earl...,1,positive sentiment
10659,3cb36356e338ef8387506ab68c84d5d0,i approached the usher and said that if she ha...,0,negative sentiment
10660,db69ef73c623fc39a04e8cac58292439,it's the unsettling images of a war-ravaged la...,1,positive sentiment
10661,f03049887fcce98a8992d1faaefb931f,my thoughts were focused on the characters . t...,1,positive sentiment

##### Removendo da anotação

In [ ]:
df_invalid = df_annotations.loc[
    df_annotations["label"] == -1 
]

df_annotations = df_annotations[
        ~df_annotations["text_id"].isin(df_invalid["text_id"])
    ].reset_index(drop=True)

In [ ]:
df_annotations

,text_id,text,label,label_description
0,6de239969386800ffdf0242777786c25,a comprehensive and provocative film -- one th...,1,positive sentiment
1,27a36737f5398d6716d230af108dfc0c,"perhaps the grossest movie ever made . funny ,...",0,negative sentiment
2,291c460bf5ce5ca42eb82c8946407e0b,the overall effect is awe and affection -- and...,1,positive sentiment
3,f806339daa6d03eb17716fcec63e6946,you have to pay attention to follow all the st...,1,positive sentiment
4,b061becd1af422a7a06f840b8cb75072,"the movie is genial but never inspired , and l...",0,negative sentiment
...,...,...,...,...
10648,63d4880669f1831d8e2e06e146a5d362,"it's a drawling , slobbering , lovable run-on ...",1,positive sentiment
10649,b505ee0f7dcbe4a8ceabd5d81d95327d,if the message seems more facile than the earl...,0,negative sentiment
10650,3cb36356e338ef8387506ab68c84d5d0,i approached the usher and said that if she ha...,0,negative sentiment
10651,db69ef73c623fc39a04e8cac58292439,it's the unsettling images of a war-ravaged la...,1,positive sentiment
10652,f03049887fcce98a8992d1faaefb931f,my thoughts were focused on the characters . t...,1,positive sentiment

#### -> Problematicas

In [ ]:
problematica_cases_path = results_dataset_path.joinpath("consensus", "problematic_cases.csv")
df_problematic = None

##### Removendo do Ground-Truth

In [ ]:
if problematica_cases_path.exists():
    df_problematic = pd.read_csv(problematica_cases_path)
    df_gt_train = df_gt_train[
        ~df_gt_train["text_id"].isin(df_problematic["text_id"])
    ].reset_index(drop=True)

In [ ]:
df_gt_train

,text_id,text,label,label_description
0,6de239969386800ffdf0242777786c25,a comprehensive and provocative film -- one th...,1,positive sentiment
1,27a36737f5398d6716d230af108dfc0c,"perhaps the grossest movie ever made . funny ,...",1,positive sentiment
2,291c460bf5ce5ca42eb82c8946407e0b,the overall effect is awe and affection -- and...,1,positive sentiment
3,f806339daa6d03eb17716fcec63e6946,you have to pay attention to follow all the st...,1,positive sentiment
4,b061becd1af422a7a06f840b8cb75072,"the movie is genial but never inspired , and l...",0,negative sentiment
...,...,...,...,...
10649,63d4880669f1831d8e2e06e146a5d362,"it's a drawling , slobbering , lovable run-on ...",1,positive sentiment
10650,b505ee0f7dcbe4a8ceabd5d81d95327d,if the message seems more facile than the earl...,1,positive sentiment
10651,3cb36356e338ef8387506ab68c84d5d0,i approached the usher and said that if she ha...,0,negative sentiment
10652,db69ef73c623fc39a04e8cac58292439,it's the unsettling images of a war-ravaged la...,1,positive sentiment
10653,f03049887fcce98a8992d1faaefb931f,my thoughts were focused on the characters . t...,1,positive sentiment

##### Removendo da anotação

In [ ]:
if problematica_cases_path.exists():
    df_problematic = pd.read_csv(problematica_cases_path)
    df_annotations = df_annotations[
        ~df_annotations["text_id"].isin(df_problematic["text_id"])
    ].reset_index(drop=True)

In [ ]:
df_annotations

,text_id,text,label,label_description
0,6de239969386800ffdf0242777786c25,a comprehensive and provocative film -- one th...,1,positive sentiment
1,27a36737f5398d6716d230af108dfc0c,"perhaps the grossest movie ever made . funny ,...",0,negative sentiment
2,291c460bf5ce5ca42eb82c8946407e0b,the overall effect is awe and affection -- and...,1,positive sentiment
3,f806339daa6d03eb17716fcec63e6946,you have to pay attention to follow all the st...,1,positive sentiment
4,b061becd1af422a7a06f840b8cb75072,"the movie is genial but never inspired , and l...",0,negative sentiment
...,...,...,...,...
10648,63d4880669f1831d8e2e06e146a5d362,"it's a drawling , slobbering , lovable run-on ...",1,positive sentiment
10649,b505ee0f7dcbe4a8ceabd5d81d95327d,if the message seems more facile than the earl...,0,negative sentiment
10650,3cb36356e338ef8387506ab68c84d5d0,i approached the usher and said that if she ha...,0,negative sentiment
10651,db69ef73c623fc39a04e8cac58292439,it's the unsettling images of a war-ravaged la...,1,positive sentiment
10652,f03049887fcce98a8992d1faaefb931f,my thoughts were focused on the characters . t...,1,positive sentiment

### - Carrega dataset de teste e validação

In [ ]:
df_eval, _ = load_hf_dataset_as_dataframe(
    dataset_name=DATASET_NAME,
    cache_dir=CACHE_DIR,
    dataset_global_config=DATASET_GLOBAL_CONFIG_EVAL,
)

print(f"Avaliação HF: {len(df_eval)}")

12:34:24 | INFO     | Carregando dataset: movie_review
12:34:30 | INFO     | Split 'test': 10662 exemplos
12:34:30 | INFO     | Categorias extraídas automaticamente: [0, 1]
12:34:30 | INFO     | Dataset embaralhado com seed=42
12:34:30 | INFO     | Amostra reduzida para 5000 exemplos
12:34:30 | INFO     | Coluna de texto: text
12:34:30 | INFO     | Ground truth carregado da coluna 'label'
12:34:30 | INFO     | DataFrame criado com 5000 linhas
Avaliação HF: 5000

In [ ]:
from sklearn.model_selection import train_test_split

df_gt_val, df_gt_test = train_test_split(
    df_eval,
    test_size=0.5,
    random_state=42,
    stratify=df_eval["label"]
)

In [ ]:
df_gt_val

,text,label,label_description
55,queen of the damned is too long with too littl...,0,negative sentiment
1128,nonchalantly freaky and uncommonly pleasurable...,1,positive sentiment
900,"its over-reliance on genre conventions , chara...",0,negative sentiment
588,"a mix of velocity and idiocy , this ruinous re...",0,negative sentiment
4174,the logic of it all will be greek to anyone no...,0,negative sentiment
...,...,...,...
3164,"a fine , rousing , g-rated family film , aimed...",1,positive sentiment
3027,beneath the film's obvious determination to sh...,1,positive sentiment
1410,would be an unendurable viewing experience for...,1,positive sentiment
495,it is a strength of a documentary to disregard...,1,positive sentiment
4722,it would work much better as a one-hour tv doc...,0,negative sentiment

In [ ]:
df_gt_test

,text,label,label_description
44,the script manages the rare trick of seeming a...,1,positive sentiment
3092,the script becomes lifeless and falls apart li...,0,negative sentiment
1915,[barry] gives assassin a disquieting authority...,1,positive sentiment
2332,the level of acting elevates the material abov...,1,positive sentiment
2263,neil burger here succeeded in . . . making the...,1,positive sentiment
...,...,...,...
4207,a clash between the artificial structure of th...,0,negative sentiment
813,the message of such reflections--intentional o...,1,positive sentiment
1248,a sequel that's much too big for its britches .\n,0,negative sentiment
673,"a combination of standard , stiff tv-style ani...",0,negative sentiment
2657,"shallow , noisy and pretentious .\n",0,negative sentiment

## 5) Converter para HuggingFace Dataset

In [ ]:
from datasets import Dataset

train_gt = Dataset.from_pandas(df_gt_train)
train_consensus = Dataset.from_pandas(df_annotations)
test_dataset = Dataset.from_pandas(df_gt_test)
eval_dataset = Dataset.from_pandas(df_gt_val)

## 6) Fine-tuning

In [ ]:
model = "roberta-base"

In [ ]:
fine_tune_output_dir = results_dataset_path.joinpath("finetuning")

Path.mkdir(fine_tune_output_dir, parents=True, exist_ok=True)

training_args = TrainingArguments(
    output_dir=fine_tune_output_dir,
    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=5e-5,
    num_train_epochs=20,

    per_device_train_batch_size=16,   
    per_device_eval_batch_size=32,

    weight_decay=0.01,

    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,

    logging_strategy="epoch",
    save_total_limit=1,

    seed=42,
)

In [ ]:
def run_fine_tuning(model, train_dataset, test_dataset, eval_dataset = None, experiment_name: str = "default"):
    fine_tuner = SupervisedFineTuner(
        model_name=model,
        training_args=training_args,
        label_schema=label_schema,
        tokenizer=HFTokenizer(
            model_name=model,
            max_length=256
        ),
        model_factory=ModelFactory,
        trainer_builder=TrainerBuilder,
        metrics_computer=MetricsComputer(),
    )

    fine_tuner.fit(train_dataset, eval_dataset)
    metrics = fine_tuner.evaluate(test_dataset)

    metrics["source"] = experiment_name

    return metrics

In [ ]:
metrics_consensus = run_fine_tuning(
    model=model,
    train_dataset=train_consensus,
    test_dataset=test_dataset,
    eval_dataset=eval_dataset,
    experiment_name="consensus_llm",
)

Map:   0%|          | 0/10653 [00:00<?, ? examples/s]

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The model is already on multiple devices. Skipping the move to device specified in `args`.

In [ ]:
metrics_gt = run_fine_tuning(
    model=model,
    train_dataset=train_gt,
    test_dataset=test_dataset,
    eval_dataset=eval_dataset,
    experiment_name="ground_truth",
)

Map:   0%|          | 0/4912 [00:00<?, ? examples/s]

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The model is already on multiple devices. Skipping the move to device specified in `args`.

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

In [ ]:
results = pd.DataFrame([metrics_consensus, metrics_gt])
results

,eval_loss,eval_accuracy,eval_f1_macro,eval_runtime,eval_samples_per_second,eval_steps_per_second,epoch,source
0,3.616076,0.6192,0.595416,35.5638,70.296,2.221,20.0,consensus_llm
1,1.859884,0.7864,0.758601,37.1634,67.270,2.126,20.0,ground_truth

In [ ]:
results.to_csv(fine_tune_output_dir.joinpath(f"{model}_fine_tuning_results.csv"), index=False)