# Fine-tuning controlado de RoBERTa (GT vs Consenso LLM)

## 1) Imports e setup

In [1]:
import pandas as pd
from transformers import TrainingArguments
from datasets import Dataset
from pathlib import Path

import sys
from loguru import logger
import pandas as pd

logger.remove()
logger.add(
    sys.stdout,
    format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>",
    level="INFO"
)

logger.success("✓ Setup completo")

# loaders
from src.utils.data_loader import load_hf_dataset_as_dataframe

# fine-tuning system
from src.fine_tune_system.fine_tune.supervised_fine_tuner import SupervisedFineTuner
from src.fine_tune_system.core.hf_tokenizer import HFTokenizer
from src.fine_tune_system.core.model_factory import ModelFactory
from src.fine_tune_system.training.trainer_builder import TrainerBuilder
from src.fine_tune_system.training.metrics import MetricsComputer
from src.fine_tune_system.training.label_schema import LabelSchema
from src.utils.dataset_aligner import DatasetAligner

12:42:26 | SUCCESS  | ✓ Setup completo

## 2) Configuração do experimento

### - Configurações de dataset

In [2]:
from src.api.schemas.dataset import DatasetConfig

DATASET_GLOBAL_CONFIG_TRAIN = DatasetConfig(
    split="train",
    combine_splits=[],
    sample_size=None,
    random_state=42,
)

DATASET_GLOBAL_CONFIG_EVAL = DatasetConfig(
    split="test",
    combine_splits=[],
    sample_size=5000,
    random_state=42,
)

### - Configurações de cache

In [3]:
CACHE_ENABLED = True
CACHE_DIR = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\.cache"

### - Resultados

In [4]:
RESULTS_DIR = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\results"

In [5]:
from src.utils.get_latest_results_date import get_latest_results_date

DATASET_NAME = "agnews"  
specific_date = "latest"

if specific_date == "latest":
    specific_date = get_latest_results_date(
        RESULTS_DIR,
        DATASET_NAME
    )
    
RESULTS_DIR = Path(RESULTS_DIR)
results_dataset_path = RESULTS_DIR.joinpath(DATASET_NAME, specific_date)

## 3) Carregar Dados

### - Carregando

In [6]:
df = pd.read_csv(results_dataset_path.joinpath("summary", "dataset_anotado_completo.csv"))

print(f"Anotado: {len(df)}")

Anotado: 5000

### - Dataset ground_truth

In [7]:
df_gt_train = (
    df[["text_id", "text", "ground_truth"]]
    .rename(columns={"ground_truth": "label"})
)

In [8]:
from src.utils.data_loader import add_label_description

df_gt_train = add_label_description(
    df_gt_train,
    dataset_name=DATASET_NAME
)

In [9]:
label_schema = LabelSchema.from_dataframe(df_gt_train)
print(label_schema.id2label)

{0: 'world', 1: 'sports', 2: 'business', 3: 'Sci/Tech'}

In [10]:
df_gt_train

,text_id,text,label,label_description
0,0,"""Sharapova takes out WTA Champs"",""Maria Sharap...",1,sports
1,1,"""Low-Cost Airline Enters Bankruptcy"",""Blaming ...",2,business
2,2,"""Sun, Nvidia Design Professional Graphics Alli...",3,Sci/Tech
3,3,"""Euro-Zone Growth Continues to Lag in 2Q (AP)""...",2,business
4,4,"""Jackson #39;s LA Lakers book blames Bryant"",""...",1,sports
...,...,...,...,...
4995,4995,"""Putin: State Firms Can Bid for YUKOS"",""Presid...",2,business
4996,4996,"""12 Killed in Fresh Iraq Violence"",""BAGHDAD, 2...",0,world
4997,4997,"""Dutrow #39;s gamble pays off fabulously"",""Des...",1,sports
4998,4998,"""Scottish driver David Coulthard signs for Red...",1,sports
4999,4999,"""Dollar Rises, Investors Eye Yields"","" NEW YOR...",2,business

### - Dataset anotado

In [11]:
df_annotations = (
    df[["text_id", "text", "most_common_annotation"]]
    .rename(columns={"most_common_annotation": "label"})
)

In [12]:
df_annotations = add_label_description(
    df_annotations,
    dataset_name=DATASET_NAME
)

In [13]:
df_annotations

,text_id,text,label,label_description
0,0,"""Sharapova takes out WTA Champs"",""Maria Sharap...",1,sports
1,1,"""Low-Cost Airline Enters Bankruptcy"",""Blaming ...",2,business
2,2,"""Sun, Nvidia Design Professional Graphics Alli...",3,Sci/Tech
3,3,"""Euro-Zone Growth Continues to Lag in 2Q (AP)""...",2,business
4,4,"""Jackson #39;s LA Lakers book blames Bryant"",""...",1,sports
...,...,...,...,...
4995,4995,"""Putin: State Firms Can Bid for YUKOS"",""Presid...",2,business
4996,4996,"""12 Killed in Fresh Iraq Violence"",""BAGHDAD, 2...",0,world
4997,4997,"""Dutrow #39;s gamble pays off fabulously"",""Des...",1,sports
4998,4998,"""Scottish driver David Coulthard signs for Red...",1,sports
4999,4999,"""Dollar Rises, Investors Eye Yields"","" NEW YOR...",2,business

### - Removendo instancias problemáticas e invalidas

#### -> Invalidas

##### Removendo do Ground-Truth

In [14]:
df_invalid_gt = df_gt_train.loc[
    df_gt_train["label"] == -1 
]

df_gt_train = df_gt_train[
        ~df_gt_train["text_id"].isin(df_invalid_gt["text_id"])
    ].reset_index(drop=True)

In [15]:
df_gt_train

,text_id,text,label,label_description
0,0,"""Sharapova takes out WTA Champs"",""Maria Sharap...",1,sports
1,1,"""Low-Cost Airline Enters Bankruptcy"",""Blaming ...",2,business
2,2,"""Sun, Nvidia Design Professional Graphics Alli...",3,Sci/Tech
3,3,"""Euro-Zone Growth Continues to Lag in 2Q (AP)""...",2,business
4,4,"""Jackson #39;s LA Lakers book blames Bryant"",""...",1,sports
...,...,...,...,...
4995,4995,"""Putin: State Firms Can Bid for YUKOS"",""Presid...",2,business
4996,4996,"""12 Killed in Fresh Iraq Violence"",""BAGHDAD, 2...",0,world
4997,4997,"""Dutrow #39;s gamble pays off fabulously"",""Des...",1,sports
4998,4998,"""Scottish driver David Coulthard signs for Red...",1,sports
4999,4999,"""Dollar Rises, Investors Eye Yields"","" NEW YOR...",2,business

##### Removendo da anotação

In [16]:
df_invalid = df_annotations.loc[
    df_annotations["label"] == -1 
]

df_annotations = df_annotations[
        ~df_annotations["text_id"].isin(df_invalid["text_id"])
    ].reset_index(drop=True)

In [17]:
df_annotations

,text_id,text,label,label_description
0,0,"""Sharapova takes out WTA Champs"",""Maria Sharap...",1,sports
1,1,"""Low-Cost Airline Enters Bankruptcy"",""Blaming ...",2,business
2,2,"""Sun, Nvidia Design Professional Graphics Alli...",3,Sci/Tech
3,3,"""Euro-Zone Growth Continues to Lag in 2Q (AP)""...",2,business
4,4,"""Jackson #39;s LA Lakers book blames Bryant"",""...",1,sports
...,...,...,...,...
4995,4995,"""Putin: State Firms Can Bid for YUKOS"",""Presid...",2,business
4996,4996,"""12 Killed in Fresh Iraq Violence"",""BAGHDAD, 2...",0,world
4997,4997,"""Dutrow #39;s gamble pays off fabulously"",""Des...",1,sports
4998,4998,"""Scottish driver David Coulthard signs for Red...",1,sports
4999,4999,"""Dollar Rises, Investors Eye Yields"","" NEW YOR...",2,business

#### -> Problematicas

In [18]:
problematica_cases_path = results_dataset_path.joinpath("consensus", "problematic_cases.csv")
df_problematic = None

##### Removendo do Ground-Truth

In [19]:
if problematica_cases_path.exists():
    df_problematic = pd.read_csv(problematica_cases_path)
    df_gt_train = df_gt_train[
        ~df_gt_train["text_id"].isin(df_problematic["text_id"])
    ].reset_index(drop=True)

In [20]:
df_gt_train

,text_id,text,label,label_description
0,0,"""Sharapova takes out WTA Champs"",""Maria Sharap...",1,sports
1,1,"""Low-Cost Airline Enters Bankruptcy"",""Blaming ...",2,business
2,2,"""Sun, Nvidia Design Professional Graphics Alli...",3,Sci/Tech
3,3,"""Euro-Zone Growth Continues to Lag in 2Q (AP)""...",2,business
4,4,"""Jackson #39;s LA Lakers book blames Bryant"",""...",1,sports
...,...,...,...,...
4984,4995,"""Putin: State Firms Can Bid for YUKOS"",""Presid...",2,business
4985,4996,"""12 Killed in Fresh Iraq Violence"",""BAGHDAD, 2...",0,world
4986,4997,"""Dutrow #39;s gamble pays off fabulously"",""Des...",1,sports
4987,4998,"""Scottish driver David Coulthard signs for Red...",1,sports
4988,4999,"""Dollar Rises, Investors Eye Yields"","" NEW YOR...",2,business

##### Removendo da anotação

In [21]:
if problematica_cases_path.exists():
    df_problematic = pd.read_csv(problematica_cases_path)
    df_annotations = df_annotations[
        ~df_annotations["text_id"].isin(df_problematic["text_id"])
    ].reset_index(drop=True)

In [22]:
df_annotations

,text_id,text,label,label_description
0,0,"""Sharapova takes out WTA Champs"",""Maria Sharap...",1,sports
1,1,"""Low-Cost Airline Enters Bankruptcy"",""Blaming ...",2,business
2,2,"""Sun, Nvidia Design Professional Graphics Alli...",3,Sci/Tech
3,3,"""Euro-Zone Growth Continues to Lag in 2Q (AP)""...",2,business
4,4,"""Jackson #39;s LA Lakers book blames Bryant"",""...",1,sports
...,...,...,...,...
4984,4995,"""Putin: State Firms Can Bid for YUKOS"",""Presid...",2,business
4985,4996,"""12 Killed in Fresh Iraq Violence"",""BAGHDAD, 2...",0,world
4986,4997,"""Dutrow #39;s gamble pays off fabulously"",""Des...",1,sports
4987,4998,"""Scottish driver David Coulthard signs for Red...",1,sports
4988,4999,"""Dollar Rises, Investors Eye Yields"","" NEW YOR...",2,business

### - Carrega dataset de teste e validação

In [23]:
df_eval, _ = load_hf_dataset_as_dataframe(
    dataset_name=DATASET_NAME,
    cache_dir=CACHE_DIR,
    dataset_global_config=DATASET_GLOBAL_CONFIG_EVAL,
)

print(f"Avaliação HF: {len(df_eval)}")

12:42:29 | Carregando dataset: agnews
12:42:33 | Split 'test': 127600 exemplos
12:42:33 | Categorias extraídas automaticamente: [0, 1, 2, 3]
12:42:33 | Amostra reduzida para 5000 exemplos (seed=42)
12:42:33 | Coluna de texto: text
12:42:33 | Ground truth carregado da coluna 'label'
12:42:33 | DataFrame criado com 5000 linhas

Avaliação HF: 5000

In [24]:
from sklearn.model_selection import train_test_split

df_gt_val, df_gt_test = train_test_split(
    df_eval,
    test_size=0.5,
    random_state=42,
    stratify=df_eval["label"]
)

In [25]:
df_gt_val

,text,label,label_description
333,"""Onuaku Picks Syracuse"",""Episcopal forward Ari...",1,sports
1867,"""Coventry Health to Buy First Health (Reuters)...",2,business
2671,"""Dual-Core Chips May Raise Software Costs"",""Fa...",3,Sci/Tech
1208,"""China Looks Outside Asia for M A (Reuters)"",""...",2,business
511,"""Friendships drive Islamic terrorists, CIA vet...",0,world
...,...,...,...
1604,"""AMD and IBM develops new technology for proce...",3,Sci/Tech
1929,"""Xstrata makes \$5.8B bid for WMC"",""TOKYO (CBS...",2,business
1486,"""Two Words from Bill Gates: Computer Science"",...",3,Sci/Tech
103,"""Japan unsatisfied with N.Korean probe"",""Japan...",0,world
2327,"""All out for 29 SA in crisis"",""SOUTH Australi...",1,sports

In [26]:
df_gt_test

,text,label,label_description
4286,"""Georgia Tech Wins Easy"",""The third-ranked Yel...",1,sports
1018,"""Now what?"",""It was an event more than eight y...",3,Sci/Tech
1081,"""Providence writes off Penn"",""Dwight Brewingto...",1,sports
483,"""Micron Strikes Deal With US in Price Fixing P...",3,Sci/Tech
2772,"""Two killed in mortar attack in Baghdad"",""Two ...",0,world
...,...,...,...
3337,"""Mars Rovers Planners Plot Crater 'Escape' (AP...",3,Sci/Tech
721,"""Internet calls add foreign accent (USATODAY.c...",3,Sci/Tech
3209,"""Syracuse rolls after fast start"",""NO. 6 SYRAC...",1,sports
20,"""Lohse Continues Roll"",""Kyle Lohse pitches sev...",1,sports
4387,"""Oil Prices Hit \$53 a Barrel, Then Stage a Re...",2,business

## 5) Converter para HuggingFace Dataset

In [27]:
from datasets import Dataset

train_gt = Dataset.from_pandas(df_gt_train)
train_consensus = Dataset.from_pandas(df_annotations)
test_dataset = Dataset.from_pandas(df_gt_test)
eval_dataset = Dataset.from_pandas(df_gt_val)

## 6) Fine-tuning

In [28]:
model = "roberta-base"

In [29]:
fine_tune_output_dir = results_dataset_path.joinpath("finetuning")

Path.mkdir(fine_tune_output_dir, parents=True, exist_ok=True)

training_args = TrainingArguments(
    output_dir=fine_tune_output_dir,
    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=5e-5,
    num_train_epochs=20,

    per_device_train_batch_size=16,   
    per_device_eval_batch_size=32,

    weight_decay=0.01,

    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,

    logging_strategy="epoch",
    save_total_limit=1,

    seed=42,
)

In [30]:
def run_fine_tuning(model, train_dataset, test_dataset, eval_dataset = None, experiment_name: str = "default"):
    fine_tuner = SupervisedFineTuner(
        model_name=model,
        training_args=training_args,
        label_schema=label_schema,
        tokenizer=HFTokenizer(
            model_name=model,
            max_length=256
        ),
        model_factory=ModelFactory,
        trainer_builder=TrainerBuilder,
        metrics_computer=MetricsComputer(),
    )

    fine_tuner.fit(train_dataset, eval_dataset)
    metrics = fine_tuner.evaluate(test_dataset)

    metrics["source"] = experiment_name

    return metrics

In [ ]:
metrics_consensus = run_fine_tuning(
    model=model,
    train_dataset=train_consensus,
    test_dataset=test_dataset,
    eval_dataset=eval_dataset,
    experiment_name="consensus_llm",
)

Map:   0%|          | 0/4989 [00:00<?, ? examples/s]

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The model is already on multiple devices. Skipping the move to device specified in `args`.

In [ ]:
metrics_gt = run_fine_tuning(
    model=model,
    train_dataset=train_gt,
    test_dataset=test_dataset,
    eval_dataset=eval_dataset,
    experiment_name="ground_truth",
)

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The model is already on multiple devices. Skipping the move to device specified in `args`.

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

In [ ]:
results = pd.DataFrame([metrics_consensus, metrics_gt])
results

,eval_loss,eval_accuracy,eval_f1_macro,eval_runtime,eval_samples_per_second,eval_steps_per_second,epoch,source
0,3.048118,0.5096,0.472486,44.2883,56.448,1.784,20.0,consensus_llm
1,2.928392,0.6812,0.674524,20.5520,121.643,3.844,20.0,ground_truth

In [ ]:
results.to_csv(fine_tune_output_dir.joinpath(f"{model}_fine_tuning_results.csv"), index=False)