# Fine-tuning controlado de RoBERTa (GT vs Consenso LLM)

## 1) Imports e setup

In [35]:
import pandas as pd
from transformers import TrainingArguments
from datasets import Dataset
from pathlib import Path

import sys
from loguru import logger
import pandas as pd

logger.remove()
logger.add(
    sys.stdout,
    format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>",
    level="INFO"
)

logger.success("✓ Setup completo")

# loaders
from src.utils.data_loader import load_hf_dataset_as_dataframe

# fine-tuning system
from src.fine_tune_system.fine_tune.supervised_fine_tuner import SupervisedFineTuner
from src.fine_tune_system.core.hf_tokenizer import HFTokenizer
from src.fine_tune_system.core.model_factory import ModelFactory
from src.fine_tune_system.training.trainer_builder import TrainerBuilder
from src.fine_tune_system.training.metrics import MetricsComputer
from src.fine_tune_system.training.label_schema import LabelSchema
from src.utils.dataset_aligner import DatasetAligner

19:30:19 | SUCCESS  | ✓ Setup completo

## 2) Configuração do experimento

### - Configurações de dataset

In [36]:
from src.api.schemas.dataset import DatasetConfig

DATASET_GLOBAL_CONFIG_TRAIN = DatasetConfig(
    split="train",
    combine_splits=[],
    sample_size=None,
    random_state=42,
)

DATASET_GLOBAL_CONFIG_EVAL = DatasetConfig(
    split="test",
    combine_splits=[],
    sample_size=5000,
    random_state=42,
)

### - Configurações de cache

In [37]:
CACHE_ENABLED = True
CACHE_DIR = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\.cache"

### - Resultados

In [38]:
RESULTS_DIR = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\results"

In [39]:
from src.utils.get_latest_results_date import get_latest_results_date

DATASET_NAME = "dblp"  
specific_date = "latest"

if specific_date == "latest":
    specific_date = get_latest_results_date(
        RESULTS_DIR,
        DATASET_NAME
    )
    
RESULTS_DIR = Path(RESULTS_DIR)
results_dataset_path = RESULTS_DIR.joinpath(DATASET_NAME, specific_date)

## 3) Carregar Dados

### - Carregando

In [40]:
df = pd.read_csv(results_dataset_path.joinpath("summary", "dataset_anotado_completo.csv"))

print(f"Anotado: {len(df)}")

Anotado: 5000

### - Dataset ground_truth

In [41]:
df_gt_train = (
    df[["text_id", "text", "ground_truth"]]
    .rename(columns={"ground_truth": "label"})
)

In [42]:
from src.utils.data_loader import add_label_description

df_gt_train = add_label_description(
    df_gt_train,
    dataset_name=DATASET_NAME
)

In [43]:
label_schema = LabelSchema.from_dataframe(df_gt_train)
print(label_schema.id2label)

{0: 'computer vision', 1: 'computational linguistics', 2: 'biomedical engineering', 3: 'software engineering', 4: 'graphics', 5: 'data mining', 6: 'security and cryptography', 7: 'signal processing', 8: 'robotics', 9: 'theory'}

In [44]:
df_gt_train

,text_id,text,label,label_description
0,0,"a bayesian approach to spectrum sensing, denoi...",7,signal processing
1,1,haplotype phase inference. most of the informa...,2,biomedical engineering
2,2,slicing object-oriented software. describes th...,3,software engineering
3,3,logical form of hierarchical relation on verbs...,1,computational linguistics
4,4,privacy-enhanced user-centric identity managem...,7,signal processing
...,...,...,...,...
4995,4995,a baseline feature set for learning rhetorical...,5,data mining
4996,4996,semi-online maintenance of geometric optima an...,9,theory
4997,4997,exact basic geometric operations on arbitrary ...,4,graphics
4998,4998,ensembles of landmark multidimensional scaling...,7,signal processing
4999,4999,on order gain of backoff misbehaving nodes in ...,7,signal processing

### - Dataset anotado

In [45]:
df_annotations = (
    df[["text_id", "text", "most_common_annotation"]]
    .rename(columns={"most_common_annotation": "label"})
)

In [46]:
df_annotations = add_label_description(
    df_annotations,
    dataset_name=DATASET_NAME
)

In [47]:
df_annotations

,text_id,text,label,label_description
0,0,"a bayesian approach to spectrum sensing, denoi...",7,signal processing
1,1,haplotype phase inference. most of the informa...,9,theory
2,2,slicing object-oriented software. describes th...,3,software engineering
3,3,logical form of hierarchical relation on verbs...,1,computational linguistics
4,4,privacy-enhanced user-centric identity managem...,6,security and cryptography
...,...,...,...,...
4995,4995,a baseline feature set for learning rhetorical...,1,computational linguistics
4996,4996,semi-online maintenance of geometric optima an...,9,theory
4997,4997,exact basic geometric operations on arbitrary ...,9,theory
4998,4998,ensembles of landmark multidimensional scaling...,0,computer vision
4999,4999,on order gain of backoff misbehaving nodes in ...,6,security and cryptography

### - Removendo instancias problemáticas e invalidas

#### -> Invalidas

##### Removendo do Ground-Truth

In [48]:
df_invalid_gt = df_gt_train.loc[
    df_gt_train["label"] == -1 
]

df_gt_train = df_gt_train[
        ~df_gt_train["text_id"].isin(df_invalid_gt["text_id"])
    ].reset_index(drop=True)

In [49]:
df_gt_train

,text_id,text,label,label_description
0,0,"a bayesian approach to spectrum sensing, denoi...",7,signal processing
1,1,haplotype phase inference. most of the informa...,2,biomedical engineering
2,2,slicing object-oriented software. describes th...,3,software engineering
3,3,logical form of hierarchical relation on verbs...,1,computational linguistics
4,4,privacy-enhanced user-centric identity managem...,7,signal processing
...,...,...,...,...
4995,4995,a baseline feature set for learning rhetorical...,5,data mining
4996,4996,semi-online maintenance of geometric optima an...,9,theory
4997,4997,exact basic geometric operations on arbitrary ...,4,graphics
4998,4998,ensembles of landmark multidimensional scaling...,7,signal processing
4999,4999,on order gain of backoff misbehaving nodes in ...,7,signal processing

##### Removendo da anotação

In [50]:
df_invalid = df_annotations.loc[
    df_annotations["label"] == -1 
]

df_annotations = df_annotations[
        ~df_annotations["text_id"].isin(df_invalid["text_id"])
    ].reset_index(drop=True)

In [51]:
df_annotations

,text_id,text,label,label_description
0,0,"a bayesian approach to spectrum sensing, denoi...",7,signal processing
1,1,haplotype phase inference. most of the informa...,9,theory
2,2,slicing object-oriented software. describes th...,3,software engineering
3,3,logical form of hierarchical relation on verbs...,1,computational linguistics
4,4,privacy-enhanced user-centric identity managem...,6,security and cryptography
...,...,...,...,...
4995,4995,a baseline feature set for learning rhetorical...,1,computational linguistics
4996,4996,semi-online maintenance of geometric optima an...,9,theory
4997,4997,exact basic geometric operations on arbitrary ...,9,theory
4998,4998,ensembles of landmark multidimensional scaling...,0,computer vision
4999,4999,on order gain of backoff misbehaving nodes in ...,6,security and cryptography

#### -> Problematicas

In [52]:
problematica_cases_path = results_dataset_path.joinpath("consensus", "problematic_cases.csv")
df_problematic = None

##### Removendo do Ground-Truth

In [53]:
if problematica_cases_path.exists():
    df_problematic = pd.read_csv(problematica_cases_path)
    df_gt_train = df_gt_train[
        ~df_gt_train["text_id"].isin(df_problematic["text_id"])
    ].reset_index(drop=True)

In [54]:
df_gt_train

,text_id,text,label,label_description
0,0,"a bayesian approach to spectrum sensing, denoi...",7,signal processing
1,2,slicing object-oriented software. describes th...,3,software engineering
2,3,logical form of hierarchical relation on verbs...,1,computational linguistics
3,4,privacy-enhanced user-centric identity managem...,7,signal processing
4,5,discovering operators and features for object ...,0,computer vision
...,...,...,...,...
4907,4995,a baseline feature set for learning rhetorical...,5,data mining
4908,4996,semi-online maintenance of geometric optima an...,9,theory
4909,4997,exact basic geometric operations on arbitrary ...,4,graphics
4910,4998,ensembles of landmark multidimensional scaling...,7,signal processing
4911,4999,on order gain of backoff misbehaving nodes in ...,7,signal processing

##### Removendo da anotação

In [55]:
if problematica_cases_path.exists():
    df_problematic = pd.read_csv(problematica_cases_path)
    df_annotations = df_annotations[
        ~df_annotations["text_id"].isin(df_problematic["text_id"])
    ].reset_index(drop=True)

In [56]:
df_annotations

,text_id,text,label,label_description
0,0,"a bayesian approach to spectrum sensing, denoi...",7,signal processing
1,2,slicing object-oriented software. describes th...,3,software engineering
2,3,logical form of hierarchical relation on verbs...,1,computational linguistics
3,4,privacy-enhanced user-centric identity managem...,6,security and cryptography
4,5,discovering operators and features for object ...,0,computer vision
...,...,...,...,...
4907,4995,a baseline feature set for learning rhetorical...,1,computational linguistics
4908,4996,semi-online maintenance of geometric optima an...,9,theory
4909,4997,exact basic geometric operations on arbitrary ...,9,theory
4910,4998,ensembles of landmark multidimensional scaling...,0,computer vision
4911,4999,on order gain of backoff misbehaving nodes in ...,6,security and cryptography

### - Carrega dataset de teste e validação

In [57]:
df_eval, _ = load_hf_dataset_as_dataframe(
    dataset_name=DATASET_NAME,
    cache_dir=CACHE_DIR,
    dataset_global_config=DATASET_GLOBAL_CONFIG_EVAL,
)

print(f"Avaliação HF: {len(df_eval)}")

19:30:20 | INFO     | Carregando dataset: dblp
19:30:31 | INFO     | Split 'test': 38128 exemplos
19:30:31 | INFO     | Categorias extraídas automaticamente: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
19:30:31 | INFO     | Amostra reduzida para 5000 exemplos (seed=42)
19:30:31 | INFO     | Coluna de texto: text
19:30:31 | INFO     | Ground truth carregado da coluna 'label'
19:30:31 | INFO     | DataFrame criado com 5000 linhas
Avaliação HF: 5000

In [58]:
from sklearn.model_selection import train_test_split

df_gt_val, df_gt_test = train_test_split(
    df_eval,
    test_size=0.5,
    random_state=42,
    stratify=df_eval["label"]
)

In [59]:
df_gt_val

,text,label,label_description
918,fixing inconsistencies in uml design models. c...,3,software engineering
1380,"analysis of algorithms, a case study: determin...",9,theory
2603,toward precise measurements using software nor...,3,software engineering
3983,cluster tracking under kinematical constraints...,8,robotics
1079,an autonomous rice transplanter guided by glob...,8,robotics
...,...,...,...
2882,multi-level biomedical ontology-enabled servic...,9,theory
2134,security status display and browser interframe...,9,theory
3525,image retrieval with relevance feedback based ...,0,computer vision
1933,pursuit-evasion on trees by robot teams. we pr...,8,robotics
819,experimental evaluation of dynamic data alloca...,5,data mining

In [60]:
df_gt_test

,text,label,label_description
4603,image categorization using local probabilistic...,0,computer vision
3483,e-conic: a perspective-aware interface for mul...,4,graphics
3777,maximum scan statistics and channel assignment...,9,theory
3457,analog performance space exploration by fourie...,4,graphics
3083,evaluation of fingerprint orientation field re...,0,computer vision
...,...,...,...
2769,remail: a reinvented email prototype. the coll...,4,graphics
2338,web search personalization with ontological us...,5,data mining
817,damocles: an observer-based approach to design...,4,graphics
417,user strategies for handling information tasks...,4,graphics
1827,a group based service triggering algorithm for...,7,signal processing

## 5) Converter para HuggingFace Dataset

In [61]:
from datasets import Dataset

train_gt = Dataset.from_pandas(df_gt_train)
train_consensus = Dataset.from_pandas(df_annotations)
test_dataset = Dataset.from_pandas(df_gt_test)
eval_dataset = Dataset.from_pandas(df_gt_val)

## 6) Fine-tuning

In [62]:
model = "roberta-base"

In [63]:
fine_tune_output_dir = results_dataset_path.joinpath("finetuning")

Path.mkdir(fine_tune_output_dir, parents=True, exist_ok=True)

training_args = TrainingArguments(
    output_dir=fine_tune_output_dir,
    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=5e-5,
    num_train_epochs=20,

    per_device_train_batch_size=16,   
    per_device_eval_batch_size=32,

    weight_decay=0.01,

    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,

    logging_strategy="epoch",
    save_total_limit=1,

    seed=42,
)

In [64]:
def run_fine_tuning(model, train_dataset, test_dataset, eval_dataset = None, experiment_name: str = "default"):
    fine_tuner = SupervisedFineTuner(
        model_name=model,
        training_args=training_args,
        label_schema=label_schema,
        tokenizer=HFTokenizer(
            model_name=model,
            max_length=256
        ),
        model_factory=ModelFactory,
        trainer_builder=TrainerBuilder,
        metrics_computer=MetricsComputer(),
    )

    fine_tuner.fit(train_dataset, eval_dataset)
    metrics = fine_tuner.evaluate(test_dataset)

    metrics["source"] = experiment_name

    return metrics

In [65]:
metrics_consensus = run_fine_tuning(
    model=model,
    train_dataset=train_consensus,
    test_dataset=test_dataset,
    eval_dataset=eval_dataset,
    experiment_name="consensus_llm",
)

Map:   0%|          | 0/4912 [00:00<?, ? examples/s]

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The model is already on multiple devices. Skipping the move to device specified in `args`.

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

In [66]:
metrics_gt = run_fine_tuning(
    model=model,
    train_dataset=train_gt,
    test_dataset=test_dataset,
    eval_dataset=eval_dataset,
    experiment_name="ground_truth",
)

Map:   0%|          | 0/4912 [00:00<?, ? examples/s]

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The model is already on multiple devices. Skipping the move to device specified in `args`.

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

In [67]:
results = pd.DataFrame([metrics_consensus, metrics_gt])
results

,eval_loss,eval_accuracy,eval_f1_macro,eval_runtime,eval_samples_per_second,eval_steps_per_second,epoch,source
0,3.616076,0.6192,0.595416,35.5638,70.296,2.221,20.0,consensus_llm
1,1.859884,0.7864,0.758601,37.1634,67.270,2.126,20.0,ground_truth

In [68]:
results.to_csv(fine_tune_output_dir.joinpath(f"{model}_fine_tuning_results.csv"), index=False)