# Fine-tuning controlado de RoBERTa (GT vs Consenso LLM)

## 1) Imports e setup

In [1]:
import pandas as pd
from transformers import TrainingArguments
from datasets import Dataset
from pathlib import Path

import sys
from loguru import logger
import pandas as pd

logger.remove()
logger.add(
    sys.stdout,
    format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>",
    level="INFO"
)

logger.success("✓ Setup completo")

# loaders
from src.utils.data_loader import load_hf_dataset_as_dataframe

# fine-tuning system
from src.fine_tune_system.fine_tune.supervised_fine_tuner import SupervisedFineTuner
from src.fine_tune_system.core.hf_tokenizer import HFTokenizer
from src.fine_tune_system.core.model_factory import ModelFactory
from src.fine_tune_system.training.trainer_builder import TrainerBuilder
from src.fine_tune_system.training.metrics import MetricsComputer
from src.fine_tune_system.training.label_schema import LabelSchema
from src.utils.dataset_aligner import DatasetAligner

12:13:06 | SUCCESS  | ✓ Setup completo

## 2) Configuração do experimento

### - Configurações de dataset

In [2]:
from src.api.schemas.dataset import DatasetConfig

DATASET_GLOBAL_CONFIG_TRAIN = DatasetConfig(
    split="train",
    combine_splits=[],
    sample_size=None,
    random_state=42,
)

DATASET_GLOBAL_CONFIG_EVAL = DatasetConfig(
    split="test",
    combine_splits=[],
    sample_size=5000,
    random_state=42,
)

### - Configurações de cache

In [3]:
CACHE_ENABLED = True
CACHE_DIR = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\.cache"

### - Resultados

In [4]:
RESULTS_DIR = "C:\\Users\\gabri\\Documents\\GitHub\\llm-annotation\\data\\results"

In [5]:
from src.utils.get_latest_results_date import get_latest_results_date

DATASET_NAME = "sst1"  
specific_date = "latest"

if specific_date == "latest":
    specific_date = get_latest_results_date(
        RESULTS_DIR,
        DATASET_NAME
    )
    
RESULTS_DIR = Path(RESULTS_DIR)
results_dataset_path = RESULTS_DIR.joinpath(DATASET_NAME, specific_date)

## 3) Carregar Dados

### - Carregando

In [6]:
df = pd.read_csv(results_dataset_path.joinpath("summary", "dataset_anotado_completo.csv"))

print(f"Anotado: {len(df)}")

Anotado: 5000

### - Dataset ground_truth

In [7]:
df_gt_train = (
    df[["text_id", "text", "ground_truth"]]
    .rename(columns={"ground_truth": "label"})
)

In [8]:
from src.utils.data_loader import add_label_description

df_gt_train = add_label_description(
    df_gt_train,
    dataset_name=DATASET_NAME
)

In [9]:
label_schema = LabelSchema.from_dataframe(df_gt_train)
print(label_schema.id2label)

{0: 'very negative sentiment', 1: 'negative sentiment', 2: 'neutral sentiment', 3: 'positive sentiment', 4: 'very positive sentiment'}

In [10]:
df_gt_train

,text_id,text,label,label_description
0,0,outside of burger 's desire to make some kind ...,1,negative sentiment
1,1,ah-nuld 's action hero days might be over .\n,1,negative sentiment
2,2,some people want the ol' ball-and-chain and th...,2,neutral sentiment
3,3,"very amusing , not the usual route in a thrill...",3,positive sentiment
4,4,"be forewarned , if you 're depressed about any...",0,very negative sentiment
...,...,...,...,...
4995,4995,must-see viewing for anyone involved in the hi...,4,very positive sentiment
4996,4996,there 's really only one good idea in this mov...,3,positive sentiment
4997,4997,-lrb- kline 's -rrb- utterly convincing -- and...,4,very positive sentiment
4998,4998,it is definitely worth seeing .\n,4,very positive sentiment
4999,4999,this dreadfully earnest inversion of the concu...,1,negative sentiment

### - Dataset anotado

In [11]:
df_annotations = (
    df[["text_id", "text", "most_common_annotation"]]
    .rename(columns={"most_common_annotation": "label"})
)

In [12]:
df_annotations = add_label_description(
    df_annotations,
    dataset_name=DATASET_NAME
)

In [13]:
df_annotations

,text_id,text,label,label_description
0,0,outside of burger 's desire to make some kind ...,1,negative sentiment
1,1,ah-nuld 's action hero days might be over .\n,1,negative sentiment
2,2,some people want the ol' ball-and-chain and th...,1,negative sentiment
3,3,"very amusing , not the usual route in a thrill...",3,positive sentiment
4,4,"be forewarned , if you 're depressed about any...",0,very negative sentiment
...,...,...,...,...
4995,4995,must-see viewing for anyone involved in the hi...,4,very positive sentiment
4996,4996,there 's really only one good idea in this mov...,3,positive sentiment
4997,4997,-lrb- kline 's -rrb- utterly convincing -- and...,3,positive sentiment
4998,4998,it is definitely worth seeing .\n,3,positive sentiment
4999,4999,this dreadfully earnest inversion of the concu...,0,very negative sentiment

### - Removendo instancias problemáticas e invalidas

#### -> Invalidas

In [14]:
df_invalid = df_annotations.loc[
    df_annotations["label"] == -1 
]

df_annotations = df_annotations[
        ~df_annotations["text_id"].isin(df_invalid["text_id"])
    ].reset_index(drop=True)

#### -> Problematicas

In [15]:
problematica_cases_path = results_dataset_path.joinpath("consensus", "problematic_cases.csv")
df_problematic = None

if problematica_cases_path.exists():
    df_problematic = pd.read_csv(problematica_cases_path)
    df_annotations = df_annotations[
        ~df_annotations["text_id"].isin(df_problematic["text_id"])
    ].reset_index(drop=True)

### - Carrega dataset de teste e validação

In [16]:
df_eval, _ = load_hf_dataset_as_dataframe(
    dataset_name=DATASET_NAME,
    cache_dir=CACHE_DIR,
    dataset_global_config=DATASET_GLOBAL_CONFIG_EVAL,
)

print(f"Avaliação HF: {len(df_eval)}")

12:13:08 | Carregando dataset: sst1
12:13:37 | Split 'test': 11855 exemplos
12:13:37 | Categorias extraídas automaticamente: [0, 1, 2, 3, 4]
12:13:37 | Amostra reduzida para 5000 exemplos (seed=42)
12:13:37 | Coluna de texto: text
12:13:37 | Ground truth carregado da coluna 'label'
12:13:37 | DataFrame criado com 5000 linhas

Avaliação HF: 5000

In [17]:
from sklearn.model_selection import train_test_split

df_gt_val, df_gt_test = train_test_split(
    df_eval,
    test_size=0.5,
    random_state=42,
    stratify=df_eval["label"]
)

In [18]:
df_gt_val

,text,label,label_description
173,cox is far more concerned with aggrandizing ma...,2,neutral sentiment
39,"much of the lady and the duke is about quiet ,...",3,positive sentiment
1099,victor rosa is leguizamo 's best movie work so...,4,very positive sentiment
4458,"the year 's happiest surprise , a movie that d...",4,very positive sentiment
874,"the irwins emerge unscathed , but the fictiona...",0,very negative sentiment
...,...,...,...
1669,both deeply weird and charmingly dear .\n,3,positive sentiment
4049,it 's a testament to de niro and director mich...,3,positive sentiment
486,without the dark spookiness of crystal lake ca...,2,neutral sentiment
2561,everything is pegged into the groove of a new ...,2,neutral sentiment
2433,a captivating coming-of-age story that may als...,4,very positive sentiment

In [19]:
df_gt_test

,text,label,label_description
24,not so much a movie as a picture book for the ...,1,negative sentiment
3023,adolescents will be adequately served by the m...,3,positive sentiment
1136,tsai ming-liang 's ghosts are painfully aware ...,2,neutral sentiment
4956,where tom green stages his gags as assaults on...,1,negative sentiment
4571,"the word that comes to mind , while watching e...",3,positive sentiment
...,...,...,...
1284,labute 's careful handling makes the material ...,4,very positive sentiment
4996,"the town has kind of an authentic feel , but e...",1,negative sentiment
2967,"thanks to ice cube , benjamins feels an awful ...",2,neutral sentiment
235,i have a confession to make : i did n't partic...,1,negative sentiment
2672,like being able to hit on a 15-year old when y...,1,negative sentiment

## 5) Converter para HuggingFace Dataset

In [20]:
from datasets import Dataset

train_gt = Dataset.from_pandas(df_gt_train)
train_consensus = Dataset.from_pandas(df_annotations)
test_dataset = Dataset.from_pandas(df_gt_test)
eval_dataset = Dataset.from_pandas(df_gt_val)

## 6) Fine-tuning

In [21]:
model = "roberta-base"

In [22]:
fine_tune_output_dir = results_dataset_path.joinpath("finetuning")

Path.mkdir(fine_tune_output_dir, parents=True, exist_ok=True)

training_args = TrainingArguments(
    output_dir=fine_tune_output_dir,
    eval_strategy="epoch",
    save_strategy="epoch",

    learning_rate=5e-5,
    num_train_epochs=20,

    per_device_train_batch_size=16,   
    per_device_eval_batch_size=32,

    weight_decay=0.01,

    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,

    logging_strategy="epoch",
    save_total_limit=1,

    seed=42,
)

In [23]:
def run_fine_tuning(model, train_dataset, test_dataset, eval_dataset = None, experiment_name: str = "default"):
    fine_tuner = SupervisedFineTuner(
        model_name=model,
        training_args=training_args,
        label_schema=label_schema,
        tokenizer=HFTokenizer(
            model_name=model,
            max_length=256
        ),
        model_factory=ModelFactory,
        trainer_builder=TrainerBuilder,
        metrics_computer=MetricsComputer(),
    )

    fine_tuner.fit(train_dataset, eval_dataset)
    metrics = fine_tuner.evaluate(test_dataset)

    metrics["source"] = experiment_name

    return metrics

In [24]:
metrics_consensus = run_fine_tuning(
    model=model,
    train_dataset=train_consensus,
    test_dataset=test_dataset,
    eval_dataset=eval_dataset,
    experiment_name="consensus_llm",
)

Map:   0%|          | 0/4759 [00:00<?, ? examples/s]

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The model is already on multiple devices. Skipping the move to device specified in `args`.

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

In [25]:
metrics_gt = run_fine_tuning(
    model=model,
    train_dataset=train_gt,
    test_dataset=test_dataset,
    eval_dataset=eval_dataset,
    experiment_name="ground_truth",
)

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The model is already on multiple devices. Skipping the move to device specified in `args`.

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

In [26]:
results = pd.DataFrame([metrics_consensus, metrics_gt])
results

,eval_loss,eval_accuracy,eval_f1_macro,eval_runtime,eval_samples_per_second,eval_steps_per_second,epoch,source
0,3.048118,0.5096,0.472486,44.2883,56.448,1.784,20.0,consensus_llm
1,2.928392,0.6812,0.674524,20.5520,121.643,3.844,20.0,ground_truth

In [27]:
results.to_csv(fine_tune_output_dir.joinpath(f"{model}_fine_tuning_results.csv"), index=False)